agbrs/agb

- Makefile
- examples/output.rs
- src/display/mod.rs
- src/display/tiled0.rs
- src/display/video.rs
- src/lib.rs
- src/mgba.rs
Add support for printing to mgba
> Mgba output

- .github/workflows/rust.yml
- examples/output.rs
- examples/panic.rs
- src/display/mod.rs
- src/interrupt.rs
- src/lib.rs
- src/single.rs
Should satify linter, and therefore reenables clippy in ci
> Satisfy linter

- examples/beep.rs
- src/lib.rs
- src/memory_mapped.rs
- src/sound/mod.rs
Adds really really basic sound support. Enough for 2 beeps at the same time!
See the beep example for how to use it
> Add sound support

- mgba-test-runner/build.rs
for me 0.9 is a symlink to 0.9.1 at the moment, which should be compatible
> change 0.9.0 to 0.9

- .github/workflows/rust.yml
> Set one target dir

- agb/examples/chicken.rs
- agb/src/display/object.rs
- agb/src/syscall.rs
Includes some treatment of affine sprites.
Does not include some clearly important other things yet.
> Further Object Implementations

- agb/examples/chicken.rs
- agb/src/bitarray.rs
- agb/src/display/object.rs
- agb/src/display/tiled0.rs
- agb/src/lib.rs
- mgba-test-runner/src/main.rs
Implements a simple allocator for objects. This will allow for objects to be obtained and dropped at will, should help quite a bit.
One thing I don't like is the requirement for lifetime parameters, but from the example this appears to not matter at all. Will have to use this to see whether I like it.
> Object allocation

- agb/src/number.rs
Adds a method to change from one base of fixnum to another along with a test.
> Add the ability to change the base of a fixnum

- agb/src/number.rs
Both very useful for various bits and bobs in the asteroids game
> Add rem and rem euclid implementations for fixnum

- agb/Cargo.lock
- agb/Cargo.toml
- agb/build.rs
Use the newest agb-image-converter
> Use image-converter 0.2.0

- agb/src/number.rs
Does what it says in the PR title
> Change base can change between convertable integer types too

- agb/src/sound/mixer.rs
Allow samples to loop if you want
> Allow channels to loop

- agb/src/number.rs
> Implement divassign for vector 2d

- agb/src/number.rs
Smaller numbers to work with :)
> Add manhattan distance method

- agb/src/number.rs
Implement integer mul and div and the corresponding mulassign and divassign along with these for vector operations.
This should be much more efficient due to being more easily optimised or a single instruction in the case of multiplication.
Furthermore this is also more accurate for these operations, which has been demonstrated over the weekend to be common.
> Integer operations for Fixed Nums

- .github/workflows/publish-agb.yml
- .github/workflows/publish-image-converter.yml
Adds actions for agb and agb-image-coverter to publish new versions when a tag is pushed
> actions to publish new versions

- release.sh
Need to include the .lock files too... :/
> Also include lock files when releasing

- agb/examples/mixer_basic.rs
- agb/src/sound/mixer/mod.rs
- agb/src/sound/mixer/sw_mixer.rs
This allows you to modify a running sound with a few checks in place to ensure that you don't do anything silly.
Example has been enhanced to show off the ability to change how a sound is being played.
> Modify running sound

- .github/workflows/linker-script.yml
- agb/build.rs
- agb/crt0.s
- agb/gba_mb.ld
- template/gba_mb.ld
> Multiboot support

- agb/Cargo.toml
I feel like I've done enough to get a slot in the authors :)
> Add myself as an author for agb

- README.md
This confused me for a bit while setting it up on a new machine
> Add CMake to the test runner instructions

- agb/src/agb_alloc/block_allocator.rs
More efficient allocator by using a linked list of free elements
TODO: combine free elements
> free list allocator

- agb/examples/chicken.rs
- agb/examples/test_logo.rs
- agb/src/display/background.rs
- agb/src/display/example_logo.rs
- agb/src/display/mod.rs
- agb/src/display/object.rs
- agb/src/display/tiled0.rs
- agb/src/display/video.rs
- agb/src/number.rs
Working branch for saner backgrounds
> Sane backgrounds

- agb/src/agb_alloc/bump_allocator.rs
Add test that if this actually is a bug in rust and it gets fixed, at least the build fails
> Add test that data_end is in the correct place

- agb/src/number.rs
Negative fixnums were printing incorrectly. Add a fix for this along with a test.
> Fix printing of negative numbers

- agb/examples/mixer_basic.rs
- agb/examples/stereo_sound.rs
- agb/src/lib.rs
- agb/src/sound/mixer/hw.rs
- agb/src/sound/mixer/mod.rs
- agb/src/sound/mixer/sw_mixer.rs
- agb/src/timer.rs
Maybe you want to be able to control the timers?
The sound forced usage of timer0, added a mechanism to make it (mostly) impossible to mis-use as I did the first time.
@corwinkuiper how important is it to you that the Gba struct is zero sized?
> Add first-class timer support

- agb/src/number.rs
> Alpha max + beta min

- .github/workflows/linker-script.yml
- examples/the-hat-chooses-the-wizard/gba.ld
We have a few copies floating around now, so check that they all match
> Check if all gba.ld and gba_mb.ld files are the same

- agb/src/lib.rs
- agb/src/number.rs
should have test to make sure it does what I want it to do
> remove the step feature

- agb/Cargo.lock
- agb/Cargo.toml
- agb/examples/output.rs
- agb/examples/wave.rs
- agb/src/agb_alloc/block_allocator.rs
- agb/src/agb_alloc/bump_allocator.rs
- agb/src/agb_alloc/mod.rs
- agb/src/display/example_logo.rs
- agb/src/interrupt.rs
- agb/src/lib.rs
> Improving allocator

- agb/src/hash_map.rs
- agb/src/lib.rs
Adds documentation and a big general comment explaining the algorithm
> Make hashmap match rust std

- agb/examples/sprites.rs
- agb/interrupt_handler.s
- agb/src/interrupt.rs
- agb/src/lib.rs
- agb/src/timer.rs
```
just run-example sprites | grep -oE '0x[0-9a-f]+' | addr2line -e target/thumbv4t-none-eabi/debug/examples/sprites -fCrp | grep -v '?? ??:0' | awk '{a[$0] += 1}END{for(key in a) print a[key], key}' | sort -g
```
> Problematic poor person's profiler

- agb/examples/animated_background.rs
- agb/examples/chicken.rs
- agb/src/display/example_logo.rs
- agb/src/display/tiled/infinite_scrolled_map.rs
- agb/src/display/tiled/map.rs
- agb/src/display/tiled/mod.rs
- agb/src/display/tiled/vram_manager.rs
- agb/src/display/video.rs
- examples/the-hat-chooses-the-wizard/src/level_display.rs
- examples/the-hat-chooses-the-wizard/src/main.rs
- examples/the-hat-chooses-the-wizard/src/splash_screen.rs
- examples/the-purple-night/src/main.rs
Simplifies tile management quite nicely
> Remove tile set ref

- agb/examples/chicken.rs
- agb/examples/sprites.rs
- agb/src/display/object.rs
- book/games/pong/src/main.rs
- examples/the-hat-chooses-the-wizard/src/main.rs
- examples/the-purple-night/src/main.rs
And some absolutely horrific unsafe code, but I think it's sound and have added some checks in debug builds that should make sure of it's soundness, although in theory there is no unused code in there from hat chooses wizard so should be quite sound.
> Z ordered sprites

- agb/src/display/object.rs
> Use unsigned_abs to satisfy clippy

- agb/.cargo/config.toml
- examples/the-hat-chooses-the-wizard/src/level_display.rs
- justfile
> Only fail ci builds on warning

- agb/examples/animated_background.rs
- agb/examples/chicken.rs
- agb/examples/dynamic_tiles.rs
- agb/examples/test_logo.rs
- agb/examples/text_render.rs
- agb/examples/wave.rs
- agb/src/display/example_logo.rs
- agb/src/display/font.rs
- agb/src/display/tiled/infinite_scrolled_map.rs
- agb/src/display/tiled/map.rs
- agb/src/display/tiled/mod.rs
- agb/src/display/tiled/tiled0.rs
- examples/the-hat-chooses-the-wizard/src/main.rs
- examples/the-purple-night/src/main.rs
Was slightly more awkward then I thought it was going to be :P
> Allow setting size of backgrounds

- agb/examples/output.rs
- agb/examples/wave.rs
- agb/src/agb_alloc/block_allocator.rs
- agb/src/agb_alloc/bump_allocator.rs
- agb/src/bitarray.rs
- agb/src/display/bitmap3.rs
- agb/src/display/bitmap4.rs
- agb/src/display/font.rs
- agb/src/display/object.rs
- agb/src/display/palette16.rs
- agb/src/display/tile_data.rs
- agb/src/display/tiled/infinite_scrolled_map.rs
- agb/src/display/tiled/map.rs
- agb/src/display/tiled/mod.rs
- agb/src/display/tiled/vram_manager.rs
- agb/src/hash_map.rs
- agb/src/input.rs
- agb/src/interrupt.rs
- agb/src/lib.rs
- agb/src/mgba.rs
- agb/src/rng.rs
- agb/src/sound/dmg.rs
- agb/src/sound/mixer/mod.rs
- agb/src/sound/mixer/sw_mixer.rs
- agb/src/syscall.rs
- agb/src/timer.rs
- examples/the-purple-night/src/main.rs
I just enabled a bunch of new lints and fixed them.
@corwinkuiper can you check if the `#[allow(clippy::trivially_copy_pass_by_ref)]` are needed in the bits you've worked on? :)
> More clippy lints

- agb/build.rs
- agb/gba.ld
- agb/gba_mb.ld
- agb/interrupt_handler.s
- agb/src/agbabi/LICENSE.md
- agb/src/agbabi/README.md
- agb/src/agbabi/memcpy.s
- agb/src/agbabi/memset.s
- agb/src/asm_include.s
- agb/src/sound/mixer/mixer.s
- agb/src/sound/mixer/sw_mixer.rs
- book/games/pong/gba.ld
- book/games/pong/gba_mb.ld
- examples/the-hat-chooses-the-wizard/gba.ld
- examples/the-purple-night/gba.ld
- examples/the-purple-night/gba_mb.ld
- justfile
- template/gba.ld
- template/gba_mb.ld
Massive performance gains across the board with this because the default rust implementation is pretty terrible on the gba
> Start using agbabi for memset and memcpy

- README.md
- template/README.md
Expand the README for agb and the template
> Flesh out the readme a little more

- agb/src/agbabi/memcpy.s
- agb/src/agbabi/memset.s
Using the official fix after reporting https://github.com/felixjones/agbabi/issues/7 rather than my hacked version
> Upgrade agbabi

- agb/examples/mixer_basic.rs
- agb/src/sound/mixer/mod.rs
- agb/src/sound/mixer/sw_mixer.rs
- agb/src/sound/mod.rs
The mixer had no (or very sparse) docs. Now it has lots
> Docs for mixer

- agb-fixnum/Cargo.toml
- agb-image-converter/Cargo.toml
- agb-macros/Cargo.toml
- agb-sound-converter/Cargo.toml
- agb/Cargo.toml
> Add repository to Cargo.toml files

- agb-fixnum/src/lib.rs
- agb-image-converter/src/lib.rs
- agb/src/display/object.rs
- agb/src/display/tiled/vram_manager.rs
- agb/src/sound/mixer/mixer.s
- agb/src/sound/mixer/mod.rs
- agb/src/sound/mixer/sw_mixer.rs
Changes made seem to be quite minor, bug fixes and small additional functions.
> Changes made for Gmtk22

- README.md
We have discussions that has Q&A. Can direct users there and we should be able to help.
> Where to go for help

- agb/src/lib.rs
This still referred to the super old implementation of objects and tiles
> Update include_gfx! documentation

- CHANGELOG.md
- agb-fixnum/src/lib.rs
- agb/src/lib.rs
Also fixes some bugs in there.
> Add docs to fixnum crate

- CHANGELOG.md
- agb/src/agb_alloc/mod.rs
- agb/src/hash_map.rs
> Custom allocator support in HashMap

- agb-sound-converter/src/lib.rs
> Emit sound as a single token, no longer require OUT_DIR hacks that Cargo doesn't intend

- CHANGELOG.md
- agb-fixnum/src/lib.rs
> take absolute values of the x, y coordinate

- CHANGELOG.md
- agb-fixnum/src/lib.rs
- agb/examples/windows.rs
- agb/src/display/blend.rs
- agb/src/display/mod.rs
- agb/src/display/video.rs
- agb/src/memory_mapped.rs
> Add blending support

- justfile
> run arm debug tests in debug mode

- CHANGELOG.md
- agb-fixnum/src/lib.rs
> Show negative sign when formatting fixnums between -1 and 0.

- .vscode/agb.code-workspace
> add all relevant directories to the code workspace

- .vscode/agb.code-workspace
> Remove agb-tests folder from the workspace

- README.md
> Add some readme badges

- agb/src/agb_alloc/bump_allocator.rs
- agb/src/display/object.rs
- agb/src/display/tiled/vram_manager.rs
- agb/src/save/flash.rs
- examples/hyperspace-roll/src/battle.rs
- examples/the-purple-night/src/main.rs
> Clippy autofix

- CHANGELOG.md
- agb/src/display/affine.rs
- agb/src/display/mod.rs
Might be interesting for @gwilymk
I'm not too keen on making any of fixnum repr C, so I provided other ways of converting to/from types for the gba.
I did the matrix multiplication myself, although I think for such a small matrix there isn't another way of doing it better.
> Some fun affine matrix functions!

- agb-fixnum/src/lib.rs
- agb/examples/affine_background.rs
- agb/src/display/affine.rs
- agb/src/display/object.rs
- agb/src/display/tiled/map.rs
- agb/src/syscall.rs
Also fixes the fact that it's completely broken
> Use the new Affine Matrix stuff in the affine background

- agb/src/display/tiled/map.rs
- examples/the-hat-chooses-the-wizard/src/level_display.rs
> Remove pointless set scroll in affine background

- examples/the-hat-chooses-the-wizard/src/main.rs
> Hide objects at the end of hat chooses the wizard

- agb-macros/src/lib.rs
Fixes https://github.com/agbrs/agb/issues/331
Doesn't feel changelog worthy.
> agb::entry should be extern "C"

- agb-fixnum/src/lib.rs
- agb/src/display/mod.rs
- agb/src/input.rs
> changes made to make new game

- agb/src/display/tiled/infinite_scrolled_map.rs
- agb/src/input.rs
- agb/src/lib.rs
- book/src/SUMMARY.md
- book/src/introduction/introduction.md
- book/src/pong/03_sprites.md
- book/src/pong/04_controls.md
- book/src/setup/building.md
Adds a section about controls and documents the input module
> Update book and document controls

- agb-image-converter/src/lib.rs
- agb-image-converter/src/rust_generator.rs
- agb/src/agb_alloc/mod.rs
- tools/src/release.rs
Fix warnings and add test to benchmark the allocator
> Fix-and-test-2023-01-06

- examples/the-hat-chooses-the-wizard/src/enemies.rs
> Derive default as now required by clippy

- examples/the-purple-night/src/lib.rs
> Fix landing 1 pixel above the ground in purple night

- CHANGELOG.md
- agb-fixnum/src/lib.rs
> make vector2d new const

- CHANGELOG.md
- agb-fixnum/src/lib.rs
- agb-image-converter/Cargo.toml
- agb-image-converter/src/colour.rs
- agb-image-converter/src/config.rs
- agb-image-converter/src/lib.rs
- agb-macros/Cargo.toml
- agb-macros/src/lib.rs
- agb-sound-converter/Cargo.toml
- agb-sound-converter/src/lib.rs
- book/games/pong/Cargo.toml
- book/src/pong/01_introduction.md
- examples/hyperspace-roll/Cargo.toml
- examples/the-hat-chooses-the-wizard/Cargo.toml
- examples/the-hat-chooses-the-wizard/build.rs
- examples/the-purple-night/Cargo.toml
- mgba-test-runner/Cargo.toml
- template/Cargo.toml
- tools/src/main.rs
Fixes a bunch of clippy lints and updates edition to 2021
> Fix clippy lints again

- CHANGELOG.md
- agb/src/display/bitmap3.rs
- agb/src/display/bitmap4.rs
- agb/src/display/blend.rs
- agb/src/display/mod.rs
- agb/src/display/object.rs
- agb/src/display/tiled/tiled0.rs
- agb/src/display/tiled/tiled1.rs
- agb/src/display/tiled/tiled2.rs
- agb/src/display/video.rs
- agb/src/display/window.rs
- agb/src/save/mod.rs
- agb/src/sound/mixer/mod.rs
- agb/src/sound/mixer/sw_mixer.rs
- agb/src/timer.rs
- examples/hyperspace-roll/src/lib.rs
- examples/hyperspace-roll/src/save.rs
- examples/hyperspace-roll/src/sfx.rs
- examples/the-hat-chooses-the-wizard/src/lib.rs
- examples/the-hat-chooses-the-wizard/src/sfx.rs
- examples/the-hat-chooses-the-wizard/src/splash_screen.rs
- examples/the-purple-night/src/lib.rs
- examples/the-purple-night/src/sfx.rs
> Add correct lifetimes to prevent double creation

- README.md
- book/src/hardware/hardware.md
- book/src/introduction/introduction.md
- book/src/pong/01_introduction.md
- book/src/pong/02_the_gba_struct.md
- book/src/pong/03_sprites.md
- book/src/setup/building.md
- book/src/setup/getting_started.md
- book/src/setup/linux.md
- book/src/setup/mac.md
> Do an editing pass of the book using chatgpt

- examples/the-purple-night/src/lib.rs
> Move mixer frame

- agb/src/agb_alloc/mod.rs
- agb/src/lib.rs
* Increases minimum nightly version
> Remove alloc error handler

- agb-image-converter/src/lib.rs
- agb/src/lib.rs
> Ensure mod tests is at the end

- agb-fixnum/Cargo.toml
- agb-gbafix/Cargo.toml
- agb-hashmap/Cargo.toml
- agb-image-converter/Cargo.toml
- agb-macros/Cargo.toml
- agb-sound-converter/Cargo.toml
- agb/Cargo.toml
- book/games/pong/Cargo.toml
- examples/combo/Cargo.toml
- examples/hyperspace-roll/Cargo.toml
- examples/the-hat-chooses-the-wizard/Cargo.toml
- examples/the-purple-night/Cargo.toml
- mgba-test-runner/Cargo.toml
- template/Cargo.toml
- tools/Cargo.toml
Just creating a PR so I can time the CI
> Maybe make the build faster by using the same settings for all crates

- mgba-test-runner/src/main.rs
- mgba-test-runner/src/runner.rs
> Make test runner sounder

- agb-hashmap/rust-toolchain.toml
> Add toolchain file for hashmap

- examples/combo/src/lib.rs
> Combo: Launch the correct game

- justfile
> Add amplitude to build

- CHANGELOG.md
Adds a bunch of things missing from the changelog
> Add more to changelog

- agb-hashmap/Cargo.toml
- agb-hashmap/benches/bench.rs
- agb-hashmap/src/lib.rs
- agb-hashmap/src/node.rs
- agb-hashmap/src/node_storage.rs
Started as an attempt to make it easier to develop the hashmap, ended up with me benchmarking everything :).
> Refactor and slightly improve hashmap

- agb-fixnum/Cargo.toml
- agb-gbafix/Cargo.toml
- agb-hashmap/Cargo.toml
- agb-image-converter/Cargo.toml
- agb-macros/Cargo.toml
- agb-sound-converter/Cargo.toml
- agb/Cargo.toml
- book/games/pong/Cargo.toml
- examples/amplitude/Cargo.toml
- examples/combo/Cargo.toml
- examples/hyperspace-roll/Cargo.toml
- examples/the-hat-chooses-the-wizard/Cargo.toml
- examples/the-purple-night/Cargo.toml
- mgba-test-runner/Cargo.toml
- template/Cargo.toml
- tools/Cargo.toml
Removes some workaronds for rust bugs
> Remove workarounds

- examples/hyperspace-roll/src/graphics.rs
Shows health in hyperspace roll
> Show health in hyperspace roll

- agb-fixnum/src/lib.rs
- agb/examples/mixer_basic.rs
- agb/src/sound/mixer/mod.rs
- agb/src/sound/mixer/sw_mixer.rs
> Upcast multiply

- examples/hyperspace-roll/src/battle.rs
- examples/hyperspace-roll/src/level_generation.rs
> Modify the enemy health rng by using a dice roll distribution

- agb-fixnum/src/lib.rs
- justfile
> add optimisation for 64 bit upcast multiply

- agb/src/agb_alloc/mod.rs
- agb/src/agbabi/mod.rs
- agb/src/display/object/unmanaged/object.rs
- agb/src/display/tiled/mod.rs
- examples/the-purple-night/src/lib.rs
Fixes the latest batch of build failures
> Fix clippy lints from 04/07/2023

- CHANGELOG.md
- agb-image-converter/src/lib.rs
- agb-image-converter/src/rust_generator.rs
Should fix https://github.com/agbrs/agb/issues/455
> Fix issue with 16x16 sprites with more than 15 colours

- agb-image-converter/Cargo.toml
- agb-macros/Cargo.toml
- agb-sound-converter/Cargo.toml
- agb/Cargo.toml
- book/book.toml
- book/games/pong/Cargo.toml
- examples/the-hat-chooses-the-wizard/Cargo.toml
- examples/the-purple-night/Cargo.toml
- tracker/agb-xm/Cargo.toml
> Use my new married name

- .github/workflows/build-and-test.yml
> Upload games as build outputs

- agb/src/sound/mixer/mixer.s
Rare case, but we probably shouldn't break everything if it happens :)
> If r2 < 4 don't overwrite all memory

- examples/the-dungeon-puzzlers-lament/src/lib.rs
- examples/the-dungeon-puzzlers-lament/src/sfx.rs
- tracker/agb-tracker/examples/basic.rs
- tracker/agb-tracker/examples/timing.rs
- tracker/agb-tracker/src/lib.rs
- tracker/agb-xm-core/src/lib.rs
Sounds way better and we can get away with it in DPL
> Use 32768Hz for the tracker

- agb/examples/object_text_render.rs
- agb/src/lib.rs
- agb/src/sync/mod.rs
> Add safety comments to public unsafe functions

- CHANGELOG.md
- agb/examples/bitmap4.rs
- agb/src/display/bitmap4.rs
Expands on #486 by updating example and updating changelog.
> Bitmap4 fix

- agb-hashmap/src/lib.rs
- agb/src/interrupt.rs
Fix the most recent batch of clippy lints
> Fix clippy lint 2023/10/07

- examples/combo/src/lib.rs
Previously amplitude could not be played!
This will make sure that we don't mess up as easily as the old version.
> Fix the combo rom

- agb/examples/affine_background.rs
> Ensure that the affine background example looks consistent

- .github/workflows/build-and-test.yml
> Override nightly versions if repo variable set for non scheduled runs

- agb/src/display/mod.rs
> Add docs for priority

- examples/the-purple-night/src/lib.rs
> Remove autoscrolling from Purple Night

- .github/workflows/build-and-test.yml
- .vscode/agb.code-workspace
- agb/src/lib.rs
- agb/src/save/flash.rs
- examples/amplitude/src/lib.rs
- examples/the-dungeon-puzzlers-lament/src/game/simulation/entity.rs
> Fix clippy and use nightly for CI builds

- agb/src/lib.rs
> fix ewram name

- agb/src/agb_alloc/block_allocator.rs
- agb/src/agb_alloc/bump_allocator.rs
- agb/src/agb_alloc/mod.rs
- agb/src/lib.rs
Perform some cleanup of the allocators
> Cleanup allocators

- agb-hashmap/src/lib.rs
- agb-image-converter/src/palette256.rs
- agb/examples/chicken.rs
- agb/src/display/affine.rs
- agb/src/display/bitmap3.rs
- agb/src/display/object/unmanaged/attributes.rs
- agb/src/input.rs
- examples/the-dungeon-puzzlers-lament/src/level.rs
Fix for latest clippy / nightly upgrade
> Remove unnecessary imports

- CHANGELOG.md
- examples/the-dungeon-puzzlers-lament/Cargo.toml
- tracker/agb-midi-core/Cargo.toml
- tracker/agb-midi-core/src/lib.rs
- tracker/agb-midi/Cargo.toml
- tracker/agb-midi/src/lib.rs
- tracker/agb-tracker-interop/src/lib.rs
- tracker/agb-tracker/Cargo.toml
- tracker/agb-tracker/src/lib.rs
Start working on MIDI file support for agb-tracker. Far from complete, but at least it is a start :).
> Midi support

- CHANGELOG.md
- agb-fixnum/Cargo.toml
- agb-fixnum/src/lib.rs
- book/games/pong/Cargo.lock
- examples/amplitude/Cargo.lock
- examples/combo/Cargo.lock
- examples/hyperspace-roll/Cargo.lock
- examples/the-dungeon-puzzlers-lament/Cargo.lock
- examples/the-hat-chooses-the-wizard/Cargo.lock
- examples/the-purple-night/Cargo.lock
from_str_radix is implemented incredibly lazily, but should hopefully be okay since you shouldn't be putting that in the critical path anyway :)
> Implement num traits for fixnum

- agb-image-converter/Cargo.toml
- agb-image-converter/src/lib.rs
- book/games/pong/Cargo.lock
- examples/amplitude/Cargo.lock
- examples/combo/Cargo.lock
- examples/hyperspace-roll/Cargo.lock
- examples/the-dungeon-puzzlers-lament/Cargo.lock
- examples/the-hat-chooses-the-wizard/Cargo.lock
- examples/the-purple-night/Cargo.lock
* Could be part of a minor version bump.
> Bump asefile version

- tools/src/publish.rs
- tools/src/release.rs
Build started failing last night because of this
> Document -> DocumentMut

- CHANGELOG.md
- agb-image-converter/src/font_loader.rs
- agb/src/display/font.rs
- agb/src/display/object/font/preprocess.rs
- agb/src/display/object/font/renderer.rs
Some fonts look a bit weird if you don't do kerning.
@corwinkuiper can you check if I've done the correct thing for object font rendering? I'm not entirely sure... Although it does render correctly in my tests :D
> Kerning support

- website/app/src/App.tsx
- website/app/src/mgba.tsx
- website/app/src/useSmoothedFramerate.hook.ts
- website/site/index.html
* Controls were broken on mobile because dpad movement was interpreted as a/b button presses.
* Fixes it to:
* Handle multiple fingers using the dpad / a / b buttons
* A dpad movement must start on the dpad, and a/b presses must start on a/b.
> Fix controls

- website/agb/src/app/mgba/mgbaWrapper.tsx
- website/agb/src/app/mobileController.tsx
- website/agb/src/app/page.tsx
> Press to start on mobile

- CHANGELOG.md
- agb-fixnum/Cargo.toml
- agb-fixnum/src/lib.rs
* Integrates num_traits more closely.
* Implements signed for our num, and the vector2d / rect abs now can use our fixnum.
* This is potentially breaking.
> Implement signed for our fix num

- website/agb/src/app/mgba/mgba.tsx
- website/agb/src/app/mgba/useController.hook.ts
- website/agb/src/app/mgba/useFrameSkip.hook.ts
- website/agb/src/app/mgba/useLocalStorage.hook.ts
- website/agb/src/app/useClientValue.hook.ts
Simple use of gamepad apis to add controller support.
> Add controller support

- CHANGELOG.md
- agb/src/mgba.rs
> Split mgba log if too big

- examples/hyperspace-roll/src/save.rs
- examples/the-dungeon-puzzlers-lament/src/lib.rs
- examples/the-dungeon-puzzlers-lament/src/save.rs
- justfile
- website/agb/src/app/mgba/mgba.tsx
- website/agb/src/app/mgba/mgbaWrapper.tsx
- website/agb/src/app/mgba/useController.hook.ts
- website/agb/src/app/mgba/useFrameSkip.hook.ts
- website/agb/src/app/page.tsx
> Get saving working

- website/agb/src/app/colour/colour.tsx
- website/agb/src/app/colour/page.tsx
> add colour converter

- book/src/hardware/hardware.md
> GBA has a 240x160px screen, not 144 (that's the original gameboy)

- .github/workflows/build-site.yml
- justfile
Use docker instead of podman for github actions build
> use docker instead of podman

- README.md
I noticed that a few of the directories weren't documented. Also did a quick edit pass
> Update repo folder descriptions

- website/agb/src/app/colour/colour.tsx
- website/agb/src/app/crash/backtrace.tsx
- website/agb/src/app/page.tsx
- website/agb/src/app/showcase/[game]/page.tsx
- website/agb/src/app/showcase/page.tsx
> switch back to the orangey colour

- website/agb/src/app/colour/colour.tsx
> Fix colour picker conversion

- agb-hashmap/Cargo.toml
- agb-hashmap/src/lib.rs
- agb-hashmap/src/node_storage.rs
- agb-hashmap/src/node_storage/vec.rs
- agb/Cargo.toml
This means hashmap can be used in stable.
> Allocator api feature for agb hashmap

- CHANGELOG.md
- agb-fixnum/src/lib.rs
> Add dot and cross product

- tracker/agb-tracker-interop/src/lib.rs
- tracker/agb-tracker/src/lib.rs
- tracker/agb-xm-core/src/lib.rs
Adds support for the effect EDx (note delay) although it isn't completely correct. And envelopes were too short so I've fixed that too.
> Add note delay and fix envelopes

- emulator/mgba/Cargo.toml
- examples/the-purple-night/Cargo.toml
- website/backtrace/Cargo.toml
Some more places where version numbers were specified too much
> Be less specific for version numbers

- agb/src/sound/mixer/sw_mixer.rs
Mentioned by @corwinkuiper that this might be a nicer way of handling this
> Use pointers rather than pin to simplify the mixers buffer handling

- CHANGELOG.md
- agb/src/panics_render.rs
- agb/src/panics_render/text.rs
> Fix qrcode generation

- CHANGELOG.md
- agb/examples/dma_effect_background_colour.rs
- agb/examples/dma_effect_background_scroll.rs
- agb/examples/dma_effect_circular_window.rs
- agb/src/dma.rs
Reverts agbrs/agb#712
This wasn't for the data but for the DMA itself
> Revert "Remove lifetime from dma transfer handle"

- CHANGELOG.md
- agb/examples/affine_background.rs
- agb/src/display/affine.rs
> Fix affine background matrix creation outside of the 1st quadrant

- CHANGELOG.md
- agb/src/display/object.rs
- agb/src/display/object/unmanaged.rs
- agb/src/display/object/unmanaged/attributes.rs
- agb/src/display/object/unmanaged/object.rs
> Expose graphics mode

- CHANGELOG.md
- agb/src/display/object/font/preprocess.rs
- agb/src/display/object/font/renderer.rs
> fix the overflow bug on kerning / xmin on a new sprite

- CHANGELOG.md
- agb-fixnum/src/lib.rs
> move some functions under more general generics

- tracker/agb-xm-core/Cargo.toml
> Fix xmrs minor version breakage

- agb/src/interrupt.rs
- agb/src/lib.rs
> Fix two build issues with latest rust version

- agb/src/agb_alloc/mod.rs
> Remove unnecessary unsafe block

- agb/src/lib.rs
> asm_const is no longer nightly

- tracker/agb-tracker-interop/src/lib.rs
- tracker/agb-tracker/src/lib.rs
- tracker/agb-xm-core/src/lib.rs
Hi,
This pull request adds support for pattern breaks and position jumps to the music tracker module. This PR only adds functionality for XM input files for now. However, these changes would also be applicable to other types of music modules, such as Amiga modules. 
In `agb-xm-core`: 
* handle effects Bxx, Dxx, and their combination
In `agb-tracker-interop`: 
* represent jump using a `PatternEffect`
In `agb-tracker`:
* keep track of any applicable jump in `TrackerInner`, and handle it in `increment_frame()` when needed
Glad for any feedback or discussion on this feature!
> Update tracker to support PatternBreak and PositionJump

- agb/src/display/affine.rs
- agb/src/display/tiled/map.rs
> Jam 2024 changes

- agb/src/interrupt.rs
- agb/src/lib.rs
- agb/src/util.rs
- emulator/mgba-sys/src/lib.rs
> Fix the CI issues with static mut access

- tools/src/release.rs
Causes the release script to update build-dependencies and the desktop tracker
> Fix release script

- CHANGELOG.md
- agb-image-converter/Cargo.toml
- agb-image-converter/src/colour.rs
- agb-image-converter/src/deduplicator.rs
- agb-image-converter/src/lib.rs
- agb-image-converter/src/palette16.rs
- agb-image-converter/src/palette256.rs
Make the whole thing more consistent and better at creating optimal palettes.
> Improve palette optimiser

- agb-hashmap/Cargo.toml
- agb-hashmap/src/lib.rs
Thought I'd add a quick property test for the hashmap. Inspired by Jonhoo's most recent stream
> Add quickcheck tests for agb_hashmap

- CHANGELOG.md
- agb-hashmap/src/hash_set.rs
- agb-hashmap/src/lib.rs
There have been at least 2 times we wanted a HashSet. So here is one.
> Add hashset

- agb/src/display/object/unmanaged/object.rs
- agb/src/syscall.rs
> remove empty lines

- agb-debug/src/gwilym_encoding.rs
- agb-hashmap/src/hash_set.rs
- agb-hashmap/src/lib.rs
- agb/src/display/blend.rs
- agb/src/display/font.rs
- agb/src/display/object/font/preprocess.rs
- agb/src/display/object/unmanaged/object.rs
- agb/src/display/tiled/map.rs
- agb/src/display/window.rs
- agb/src/dma.rs
- agb/src/panics_render/text.rs
- agb/src/save/mod.rs
- agb/src/sync.rs
- examples/the-dungeon-puzzlers-lament/src/game.rs
- examples/the-hat-chooses-the-wizard/src/lib.rs
- tracker/agb-tracker/src/lib.rs
> Clippy wants us to elide lifetimes

- agb/examples/dma_effect_circular_window.rs
This was causing the build to fail
> isqrt is now stable

- CHANGELOG.md
- agb-hashmap/Cargo.toml
- agb-hashmap/src/lib.rs
- agb-hashmap/src/serde.rs
- justfile
Probably worth having serde support in agb_hashmap.
> Optional serde support agb hashmap

- agb-fixnum/Cargo.toml
- agb-hashmap/Cargo.toml
- agb/Cargo.toml
Might be nice to have these keywords show up in crates.io
> Add some keywords to the main agb crates

- agb-hashmap/src/lib.rs
> Fix clippy lint issue

- website/backtrace/Cargo.toml
> Mark wasm lint issues as expected

- CHANGELOG.md
- agb/src/display/tiled/vram_manager.rs
> Set background palette

- agb/examples/dma_effect_circular_window.rs
- agb/examples/dynamic_tiles.rs
- agb/src/bitarray.rs
- agb/src/display/bitmap4.rs
- agb/src/display/object/sprites/sprite_allocator.rs
- agb/src/display/window.rs
- agb/src/dma.rs
- agb/src/save/flash.rs
- agb/src/sound/dmg.rs
- agb/src/sound/mixer/hw.rs
- tracker/agb-midi-core/src/lib.rs
> Fix clippy lints

- CHANGELOG.md
- agb/src/backtrace.rs
> Simplify backtrace code and make it work on arm and thumb (mixed too)

- CHANGELOG.md
- agb-fixnum/Cargo.toml
- agb-fixnum/src/lib.rs
- agb/Cargo.toml
> Optional serde support in agb-fixnum

- emulator/mgba/src/lib.rs
- emulator/mgba/src/vfile.rs
- examples/hyperspace-roll/src/level_generation.rs
- examples/the-dungeon-puzzlers-lament/src/map.rs
> Fix clippy lints as-of 2025-02-01

- .github/workflows/build-site.yml
- .github/workflows/publish-agb.yml
- justfile
- website/agb/src/app/examples/[example]/page.tsx
- website/agb/src/sluggify.ts
> Site include latest released version

- website/agb/src/app/examples/[example]/emulator.tsx
- website/agb/src/app/page.tsx
- website/agb/src/components/mgba/mgba.tsx
- website/agb/src/components/mgba/mgbaWrapper.tsx
- website/mgba-wasm/BuildMgbaWasm
> Website mgba log messages

- .gitmodules
- emulator/mgba-sys/.gitignore
- emulator/mgba-sys/build.rs
> stop using submodule

- agb/examples/chicken.rs
- agb/examples/infinite_scrolled_map.rs
- agb/examples/sprites.rs
> use fixnum as exported from agb in examples

- website/agb/src/app/examples/[example]/emulator.tsx
- website/agb/src/app/examples/[example]/page.tsx
- website/agb/src/app/examples/[example]/styles.tsx
- website/agb/src/components/mgba/mgba.tsx
- website/agb/src/components/resizable.tsx
The example playgrounds will now work a lot better on mobile, having a controller and separate tabs for the code and game.
> Improve mobile experience

- examples/the-dungeon-puzzlers-lament/src/game/simulation/entity.rs
> Fix clippy lints for 2025-03-04

- website/play/docker/AgbBuild.dockerfile
Reverts agbrs/agb#855
https://github.com/rust-lang/rustup/issues/4211
> Revert "Update rust Docker tag to v1.85.0"

- CODE_OF_CONDUCT.md
A code of conduct will be useful for the future as we start to grow the project. With the newer release coming out, we're hoping to make agb much easier to use and we'd like to foster a helpful and kind community.
I've based this heavily on other code of conducts I've found and agreed with. Hopefully this will be strong enough for now with the size that the agb community currently is and we can always update it as we grow :D.
> Add a code of conduct for AGB

- emulator/test-runner/src/main.rs
> test-runner show percentage of frame time

- examples/hyperspace-roll/src/battle.rs
- examples/hyperspace-roll/src/battle/display.rs
> fix hyperspace roll dice positions

- agb/examples/affine_background.rs
- agb/examples/chicken.rs
- agb/examples/dma_effect_background_colour.rs
- agb/examples/dma_effect_background_scroll.rs
- agb/examples/dma_effect_circular_window.rs
- agb/examples/dynamic_tiles.rs
- agb/examples/infinite_scrolled_map.rs
- agb/examples/mixer_32768.rs
- agb/examples/object_text_render.rs
- agb/examples/save.rs
- agb/examples/stereo_sound.rs
- agb/examples/text_render.rs
- agb/examples/windows.rs
- agb/src/display/mod.rs
- agb/src/display/object/font.rs
- agb/src/no_game.rs
- examples/amplitude/src/lib.rs
- examples/combo/src/lib.rs
- examples/hyperspace-roll/src/battle.rs
- examples/hyperspace-roll/src/customise.rs
- examples/hyperspace-roll/src/lib.rs
- examples/the-dungeon-puzzlers-lament/src/lib.rs
- examples/the-hat-chooses-the-wizard/src/lib.rs
- examples/the-hat-chooses-the-wizard/src/splash_screen.rs
- examples/the-purple-night/src/lib.rs
> graphics frame includes waiting for vblank

- .github/workflows/build-site.yml
- agb/src/sync.rs
- emulator/mgba-sys/build.rs
- justfile
> Inline does nothing here and is now a warning (so error on CI)

- agb/examples/object_text_render.rs
- agb/src/display/font.rs
- agb/src/display/font/align.rs
- agb/src/display/font/layout.rs
- agb/src/display/font/special.rs
> Font tagging

- agb/examples/dma_effect_circular_window.rs
- agb/examples/windows.rs
- agb/src/display/mod.rs
- agb/src/display/window.rs
Update windows to match the new style API
> Refactor windows to new frame API

- agb/examples/dma_effect_background_colour.rs
- agb/examples/dma_effect_background_scroll.rs
- agb/examples/dma_effect_circular_window.rs
- agb/src/display/mod.rs
- agb/src/dma.rs
- agb/src/lib.rs
- agb/src/panics_render.rs
DMA needed some work to be nice and easy to use. Hopefully it is now.
> Refactor dma for frame

- CHANGELOG.md
- agb-image-converter/src/lib.rs
- agb-image-converter/src/rust_generator.rs
- agb-image-converter/src/sprite/multi.rs
- agb-image-converter/src/sprite/regular.rs
- agb/examples/chicken.rs
- agb/examples/dynamic_tiles.rs
- agb/examples/mixer_32768.rs
- agb/examples/object_text_render.rs
- agb/examples/save.rs
- agb/examples/stereo_sound.rs
- agb/examples/text_render.rs
- agb/src/display/colours.rs
- agb/src/display/font/sprite.rs
- agb/src/display/font/tiled.rs
- agb/src/display/mod.rs
- agb/src/display/object/sprites/sprite.rs
- agb/src/display/palette16.rs
- agb/src/display/tiled/vram_manager.rs
- agb/src/no_game.rs
- examples/amplitude/src/lib.rs
- examples/the-dungeon-puzzlers-lament/src/game.rs
- examples/the-purple-night/src/lib.rs
This is nice for giving us slightly clearer type signatures
> Colour15 newtype

- agb/src/display/font/sprite.rs
- agb/src/display/object.rs
- agb/src/display/object/sprites.rs
- agb/src/display/object/sprites/sprite.rs
- agb/src/display/object/sprites/sprite_allocator.rs
- agb/src/display/object/sprites/sprite_allocator/dynamic.rs
- agb/src/display/object/sprites/sprite_allocator/sprite.rs
- agb/src/no_game.rs
> Object improvements

- agb/examples/save.rs
> use crab in save example

- agb/src/display/object.rs
- agb/src/display/object/sprites.rs
- agb/src/display/object/sprites/sprite.rs
> repeating animation iterator

- CHANGELOG.md
- agb-fixnum/src/lib.rs
> Num rounding

- agb/examples/object_text_render.rs
- examples/amplitude/src/lib.rs
- examples/the-purple-night/src/lib.rs
- justfile
> use rounding where the rounding pattern was used

- CHANGELOG.md
- agb-fixnum/src/lib.rs
- agb/examples/chicken.rs
> Fixnum rect clamp method

- agb-image-converter/src/lib.rs
- agb/examples/affine_background.rs
- agb/examples/animated_background.rs
- agb/examples/chicken.rs
- agb/examples/dma_effect_background_colour.rs
- agb/examples/fixnums.rs
- agb/examples/frame_lifecycle.rs
- agb/examples/infinite_scrolled_map.rs
- agb/src/display/example_logo.rs
- agb/src/display/tiled/regular_background.rs
- agb/src/display/tiled/regular_background/test.rs
- agb/src/lib.rs
- examples/combo/src/lib.rs
- examples/hyperspace-roll/src/background.rs
- examples/the-dungeon-puzzlers-lament/src/backgrounds.rs
- examples/the-hat-chooses-the-wizard/src/lib.rs
- examples/the-hat-chooses-the-wizard/src/splash_screen.rs
- examples/the-purple-night/src/lib.rs
> `mod` keyword in background import

- book/src/articles/fixed_point_numbers.md
Small amount of extra text to cover more information about fixnums and to tweak the grammar a little
> Added a bit more about fixnums

- agb-debug/src/main.rs
- agb-fixnum/src/lib.rs
- agb-image-converter/src/sprite/multi.rs
- agb-image-converter/src/sprite/regular.rs
- emulator/test-runner/src/main.rs
- examples/the-dungeon-puzzlers-lament/build.rs
> Fix clippy lints for 2025-04-24

- agb/dictionary.txt
- book/src/articles/fixed_point_numbers.md
- book/src/pong/07_paddle_collision.md
- cspell.json
The ignore regexes were over-eager and skipping some things. So fix those and then fix all the issues that came up because we're checking better now
> Fix some cases where the regexes were including the wrong things

- .github/workflows/build-and-test.yml
> fix ci for PRs by using old nightly

- agb-image-converter/src/lib.rs
- agb/src/lib.rs
> Include background gfx docs and visibility

- agb-sound-converter/src/lib.rs
- agb/examples/mixer_32768.rs
- agb/examples/mixer_basic.rs
- agb/examples/stereo_sound.rs
- agb/src/lib.rs
- agb/src/sound/mixer/mod.rs
- agb/src/sound/mixer/sw_mixer.rs
- examples/hyperspace-roll/src/sfx.rs
- examples/the-dungeon-puzzlers-lament/src/sfx.rs
- examples/the-hat-chooses-the-wizard/src/sfx.rs
- examples/the-purple-night/src/sfx.rs
- tracker/agb-tracker/examples/timing.rs
- tracker/agb-tracker/src/lib.rs
Adds a nice bit of type safety and makes it more obvious what to do with various values.
> SoundData rather than u8

- CHANGELOG.md
Forgot to push the changelog entry
> Add a changelog entry for `SoundData`

- .github/workflows/build-and-test.yml
> switch back to latest nightly

- agb/.cargo/config.toml
- agb/src/agb_alloc/mod.rs
- agb/src/display/colours.rs
- agb/src/display/tiled.rs
- agb/src/display/tiled/regular_background.rs
- agb/src/display/tiled/vram_manager.rs
- agb/src/doctest_runner.rs
- agb/src/input.rs
- agb/src/interrupt.rs
- agb/src/lib.rs
- agb/src/sound/mixer/mod.rs
- agb/src/sound/mixer/sw_mixer.rs
- template/.cargo/config.toml
I realised I can actually make the doctests run which is cool.
It's a bit of work to make it happen, but I've updated the template in case someone else wants to do this too.
> Actually run doctests

- agb/examples/affine_object.rs
- agb/examples/chicken.rs
- agb/examples/dma_effect_blob_monster.rs
- agb/examples/fixnums.rs
- agb/examples/frame_lifecycle.rs
- agb/examples/hud.rs
- agb/examples/object_text_render.rs
- agb/examples/save.rs
- agb/src/display/font/sprite.rs
- agb/src/display/object/unmanaged/object.rs
- agb/src/no_game.rs
- book/games/pong/src/main.rs
- book/src/articles/objects_deep_dive.md
- book/src/pong/03_sprites.md
- book/src/pong/04_controls.md
- book/src/pong/05_meta_sprites.md
- book/src/pong/07_paddle_collision.md
- book/src/pong/08_paddle_movement.md
- examples/amplitude/src/lib.rs
- examples/hyperspace-roll/src/battle.rs
- examples/hyperspace-roll/src/battle/display.rs
- examples/hyperspace-roll/src/customise.rs
- examples/hyperspace-roll/src/graphics.rs
- examples/the-dungeon-puzzlers-lament/src/game.rs
- examples/the-dungeon-puzzlers-lament/src/game/game_state.rs
- examples/the-dungeon-puzzlers-lament/src/game/simulation/animation.rs
- examples/the-hat-chooses-the-wizard/src/lib.rs
- examples/the-purple-night/src/lib.rs
In backgrounds it's called `pos` so rename it to be the same in objects
> Rename set_position to set_pos in Object

- CHANGELOG.md
- agb-fixnum/src/num.rs
> Panic if N is too big and you're trying to do multiplication or division

- agb/dictionary.txt
> update dictioary with relevant terms

- .github/workflows/build-site.yml
- justfile
> make site easier to run locally

- agb-image-converter/src/sprite/common.rs
- agb-image-converter/src/sprite/multi.rs
- agb-image-converter/src/sprite/regular.rs
- agb/src/display/object/unmanaged/object.rs
> register interest in the input files

- CHANGELOG.md
- agb/src/lib.rs
- agb/src/panics_render.rs
- agb/src/syscall.rs
- agb/tests/test_multiboot.rs
- agb/tests/test_save_eeprom_512b.rs
- agb/tests/test_save_eeprom_8k.rs
- agb/tests/test_save_flash_128k.rs
- agb/tests/test_save_flash_64k.rs
- agb/tests/test_save_sram.rs
- tracker/agb-tracker/src/lib.rs
> 'Document' syscall module

- agb/src/display/font.rs
- agb/src/display/font/align.rs
- agb/src/display/font/layout.rs
- agb/src/display/font/special.rs
- agb/src/display/font/sprite.rs
- agb/src/display/font/tiled.rs
> add doc comments for all of font rendering

- agb/src/lib.rs
> add doc comment for `include_font`

- agb/dictionary.txt
- agb/src/agb_alloc/mod.rs
- agb/src/display/colours.rs
- agb/src/lib.rs
- agb/src/no_game.rs
- agb/src/print.rs
Make the whole thing more consistent. Now the crate level docs look really nice :D
> Crate level docs improvements

- agb/examples/dma_effect_pipe_background.rs
- agb/src/display/affine.rs
- agb/src/display/tiled.rs
- agb/src/display/tiled/affine_background.rs
- agb/src/syscall.rs
> Move `AffineMatrixBackground` to the `affine_background` module

- book/src/articles/fixed_point_numbers.md
- book/src/pong/10_fixnums.md
- book/src/pong/12_keeping_score.md
Corwin mentioned this to me on review of the fixnum chapter of the tutorial
> Round instead of floor

- book/src/hardware/hardware.md
- book/src/pong/02_the_gba_struct.md
- book/src/pong/03_sprites.md
- book/src/pong/04_controls.md
- book/src/pong/05_meta_sprites.md
- book/src/pong/07_paddle_collision.md
- book/src/setup/building.md
I had a look over the book and made some edits for style and correctness.
> Book: edit pass after proof read

- agb/src/print.rs
* Links to eprintln docs
* Removes empty lines
> neaten the println doc comments

- agb/examples/chicken.rs
Gives some hints around what can be experimented with
> add things that can be experimented with to chicken example comments

- agb/src/syscall.rs
Small syscall.rs updates to clean it up a little
> Use clobber_abi and references directly

- .github/workflows/build-and-test.yml
- Cargo.toml
- agb/src/agb_alloc/block_allocator.rs
- agb/src/sound/mixer/sw_mixer.rs
- examples/the-dungeon-puzzlers-lament/src/game/game_state.rs
- examples/the-dungeon-puzzlers-lament/src/game/simulation/entity.rs
- examples/the-purple-night/src/lib.rs
- justfile
- tracker/agb-tracker/src/lib.rs
- tracker/desktop-player/rust-toolchain.toml
- tracker/desktop-player/src/mixer.rs
> if-let chains!

- agb/dictionary.txt
- agb/examples/blend_rain.rs
- agb/examples/mixer_32768.rs
- agb/examples/mixer_basic.rs
- agb/src/lib.rs
- agb/src/sound/mixer/mod.rs
- agb/src/sound/mixer/sw_mixer.rs
- book/games/pong/src/main.rs
- book/src/SUMMARY.md
- book/src/articles/music_and_sfx.md
- examples/hyperspace-roll/src/lib.rs
- examples/the-dungeon-puzzlers-lament/src/sfx.rs
- examples/the-hat-chooses-the-wizard/src/lib.rs
- examples/the-purple-night/src/lib.rs
- tracker/agb-tracker/examples/basic.rs
- tracker/agb-tracker/examples/timing.rs
- tracker/agb-tracker/src/lib.rs
I also removed `mixer.enable()` because I don't think it's useful.
> Mixer article

- agb-fixnum/src/num.rs
> Fix sqrt panic documentation

- book/src/SUMMARY.md
- book/src/articles/vscode_debugger.md
- template/.vscode/extensions.json
- template/.vscode/launch.json
- template/.vscode/tasks.json
> Vscode debug article

- book/games/platform/build.rs
- book/games/platform/src/main.rs
- justfile
> Include the platform game in the build

- agb/src/sound/mixer/sw_mixer.rs
> Allow more buffer copy cases in the mixer

- agb-hashmap/src/node_storage.rs
- agb/examples/animated_background.rs
- agb/src/agb_alloc/mod.rs
- examples/hyperspace-roll/src/battle.rs
- examples/hyperspace-roll/src/level_generation.rs
- examples/hyperspace-roll/src/lib.rs
- examples/the-dungeon-puzzlers-lament/build.rs
- examples/the-dungeon-puzzlers-lament/src/lib.rs
- tracker/agb-tracker/src/lib.rs
> Clippy fixes for 2025-06-28

- book/src/pong/02_sprites.md
- book/src/pong/03_meta_sprites.md
- book/src/pong/04_paddle_movement.md
- book/src/pong/05_paddle_collision.md
- book/src/pong/06_background.md
- book/src/pong/07_fixnums.md
- book/src/pong/08_bgm.md
- book/src/pong/09_keeping_score.md
I hope you will find my changes useful :smile:
> Fixed minor issues in Pong tutorial book

- agb/src/input.rs
Probably worth just having an exhaustive test here :). Currently failing due to https://github.com/agbrs/agb/issues/1056 but we can merge it once rustc is fixed
> Add tests for `From<(bool, bool)> for Tri`

- CHANGELOG.md
- tracker/agb-tracker/src/lib.rs
> Fix agb tracker speeds faster than 150 BPM

- .github/workflows/build-site.yml
Hopefully my untested bash code works
> Switch to the old version of nightly

- .github/scripts/nightly-of-last-release.sh
- .github/workflows/build-site.yml
- .github/workflows/playground.yml
- agb-hashmap/src/node_storage.rs
- agb-image-converter/src/font_loader.rs
- agb-image-converter/src/lib.rs
- agb/src/agbabi/mod.rs
- agb/src/global_asm.rs
> Nightly fixes

- book/src/pong/05_paddle_collision.md
- book/src/pong/09_keeping_score.md
Clarifies a confusing section and fixes an incorrect field in one place.
> Minor book fixes
