agbrs/agb

gba.ld
src/lib.rs

Change the implicit location of statics to ewram, as it is huge! Also fixes related test

Change implicit location

---

agb/examples/chicken.rs
agb/examples/test_logo.rs
agb/src/display/tiled0.rs

Handy way of handling maps for games. Automatically handles copying correct portion of map and the horizontal and vertical offset registers.
Also fixes relevant examples.
No example is provided with this funtionality showing.

Better Backgrounds for large maps

---

.github/workflows/rust.yml
agb/rust-toolchain.toml

This should mean that user no longer needs to change default channel to build iff rustup is installed.
Also removes rust install step from action, because hopefully this will also work by default.

add rust-toolchain.toml

---

agb/src/number.rs

A few improvements:
1. Implements multiply and divide in a way that maximises precision
2. Implements the assign variants in terms of the non assign variants
3. Implements the traits against anything that implements Into<Num<N>> which allows us to write things like `one + 3` without needing the `.into()` everywhere :D

Improve fixnum

---

agb-image-converter/Cargo.lock
agb-image-converter/Cargo.toml
agb-image-converter/src/lib.rs
agb-image-converter/src/rust_generator.rs

agb-image-converter defaults to `crate::foo` but outside the agb crate, that should be `agb::`.
Future PR will take advantage of this change in agb along with the refactor to using a builder rather than what we have at the moment.

Allow agb image converter to be used in any crate

---

agb-image-converter/Cargo.lock
agb-image-converter/Cargo.toml

We don't need to support every image format under the sun, so just keep bmp and png for now

Massively reduce the number of dependencies used by agb-image-converter

---

agb/src/syscall.rs

Makes it a little more obvious what arguments the affine matrix syscall accepts.
Also fix a potential issue where the input struct wasn't correctly packed so could randomly break due to non-fixed ordering of the fields

Improve affine matrix syscall arguments

---

agb/src/number.rs
agb/src/syscall.rs

Was a bit of a pain, but lets you use any of `[iu](16|32)` to back your fixnum

Allow multiple integer sizes for fixnum

---

agb/src/sound/mod.rs

Didn't realise that sweep and envelope use different definitions for increasing and decreasing...

Sweep works backwards

---

agb/src/number.rs

Multiplication overflowed super easily (Number<8> could only multiply up to 255 * 255, Number<10> only up to 31 * 31) which is far from ideal. This pushes that ability to `2^((width - N) / 2)`.
The formula is just (a + b)(c + d) = ac + ad + bc + bd. This makes multiplications much more intensive, but hopefully doesn't matter too much (a divide is still 100 times worse :P)

Make it so that multiplication doesn't overflow so easily

---

agb/src/sound/mixer.rs

Was causing the example to panic :roll_eyes:

Handle sounds of length not exactly a multiple of SOUND_BUFFER_SIZE

---

agb/src/sound/mixer/mod.rs
agb/src/sound/mixer/sw_mixer.rs

Lets you play multiple sounds at once by declaring a channel as 'high' priority. A high priority channel will never be overwritten and will overwrite a low priority one if we run out of the 16 available channels.

Add sound priorities

---

agb/build.rs
agb/crt0.s
agb/examples/mixer_basic.rs
agb/src/number.rs
agb/src/sound/mixer/mixer.s
agb/src/sound/mixer/sw_mixer.rs

The asm code was generated by writing the equivalent code in C and then copy pasting it from godbolt. I then went and added comments and also reduced the collapse function by 1 instruction :)

Speed up the mixer by writing the core loops in ASM

---

release.sh

I noticed when I last did a release that the agb dependency wasn't updated which caused the build to fail.
Now if you release a new version of say agb-macros, the `agb_macros` line in agb's Cargo.toml file will be updated to state the new version, so you can ensure the build always works :tada:

Update agb when releasing

---

agb/build.rs
agb/crt0.s
agb/src/asm_include.s
agb/src/sound/mixer/mixer.s
agb/src/sound/mixer/sw_mixer.rs

Reduce the number of multiplications by 176 per sample playing
Should set us up nicely in the near future for being able to increase the sample rate without causing a slow down.
I've also added some extra asm macros for correctly defining a function which should help with debug info and if you ever want to run it in a debugger.

Half multiplications in sound mixing

---

agb/src/sound/mixer/mixer.s
agb/src/sound/mixer/sw_mixer.rs

If you're making the same modification to both the left and the right channel, and it is a perfect power of 2, then don't multiply and instead do a shift. Should actually be noticeably faster

Special case simple mixer

---

agb/examples/mixer_basic.rs
agb/examples/stereo_sound.rs
agb/src/sound/mixer/sw_mixer.rs
examples/the-hat-chooses-the-wizard/src/main.rs
examples/the-hat-chooses-the-wizard/src/sfx.rs
examples/the-hat-chooses-the-wizard/src/splash_screen.rs
examples/the-purple-night/src/main.rs
examples/the-purple-night/src/sfx.rs

vblank time is in short supply and so we should minimise the work that actually needs to be done in it.
This splits the mixer so that now the recommended method of using it is:
```rust
mixer.frame(); // super expensive operation requiring about 10% of frame time in worst case
vblank.wait_for_vblank();
mixer.after_vblank(); // super cheap operation requiring about 20 instructions
```
rather than before where it was
```rust
vblank.wait_for_vblank();
mixer.vblank(); // do both steps here which takes pretty much all of vblank in the best case
```

Allow the sound mixer to do work during vdraw

---

agb/crt0.s

The WAITCNT register controls how long it takes to access ROM and SRAM. It defaults to the maximum which is 8 cycles per random access, and 8 per sequential.
Lower this to 3 cycles per random access and 1 per sequential and enable prefetching. According to gbatek, 0x4317 is used by most commercial games.

Set waitstate to 0x4317 as is standard in most games

---

agb/examples/allocation.rs
agb/examples/beep.rs
agb/examples/bitmap3.rs
agb/examples/bitmap4.rs
agb/examples/chicken.rs
agb/examples/mixer_basic.rs
agb/examples/multiple_video.rs
agb/examples/output.rs
agb/examples/panic.rs
agb/examples/stereo_sound.rs
agb/examples/syscall.rs
agb/examples/test_logo.rs
agb/examples/wave.rs
agb/src/display/object.rs
agb/src/lib.rs
book/games/pong/src/main.rs
book/src/pong/02_the_gba_struct.md
examples/the-purple-night/src/main.rs
template/src/main.rs

Seems either we're misremembering that this was required for panic handler reasons or it was fixed at some point in nightly

You don't need `extern crate agb;` any more

---

agb-macros/src/lib.rs
agb/examples/allocation.rs
agb/examples/beep.rs
agb/examples/bitmap3.rs
agb/examples/bitmap4.rs
agb/examples/chicken.rs
agb/examples/mixer_basic.rs
agb/examples/multiple_video.rs
agb/examples/output.rs
agb/examples/panic.rs
agb/examples/stereo_sound.rs
agb/examples/syscall.rs
agb/examples/test_logo.rs
agb/examples/wave.rs
agb/src/lib.rs
book/games/pong/src/main.rs
book/src/pong/02_the_gba_struct.md
examples/the-hat-chooses-the-wizard/src/main.rs
examples/the-purple-night/src/main.rs
template/src/main.rs

Change it so that you don't have to create the `Gba` struct yourself, you instead have it created for you by the `#[agb::entry]` macro

Make agb entry create gba struct

---

agb/src/lib.rs

fix a syntax error in the documentation and also add a useful link

Fix the entry link and the syntax

---

agb-fixnum/src/lib.rs
agb/src/sound/mixer/mod.rs

I checked the output of both hat chooses wizard and purple night for obvious places where the compiler decided not to inline. These turn out to be particularly bad places.

Strategic inlines

---

agb/Cargo.toml
agb/src/display/object.rs
agb/src/hash_map.rs
agb/src/lib.rs
book/games/pong/Cargo.lock
examples/the-hat-chooses-the-wizard/Cargo.lock
examples/the-purple-night/Cargo.lock

hashbrown appears on the top of the profile quite frequently, and it seems the design, although really good on modern hardware, doesn't work well for something like the GBA.
This is a much simpler hash map implementation (based on the same ideas as hashbrown, a robin hood hash), but better optimised for the GBA hardware.
There is still some work to do on it, but this is probably a good first step :).

Custom hashmap

---

agb/examples/dynamic_tiles.rs
agb/src/display/tiled/vram_manager.rs

Things I don't like:
* You have to call `.remove_dynamic_tile` or you'll like vram (I guess similar to how you have to call `.clear` on a background)
* You can trigger weird behaviour if you pass the tileset from the dynamic tile with a tile index unequal to the given one
But it does work, I'll try and write a font example soon.

Add a slightly crappy dynamic tiles API

---

agb/examples/animated_background.rs
agb/examples/chicken.rs
agb/examples/dynamic_tiles.rs
agb/examples/text_render.rs
agb/src/display/example_logo.rs
agb/src/display/font.rs
agb/src/display/tiled/infinite_scrolled_map.rs
agb/src/display/tiled/map.rs
agb/src/display/tiled/vram_manager.rs
examples/the-hat-chooses-the-wizard/src/main.rs
examples/the-hat-chooses-the-wizard/src/splash_screen.rs
examples/the-purple-night/src/main.rs

It was possible to free and change a tile that was currently being rendered. Will now only free tiles on `commit()`

Stop freeing still in use tiles

---

agb/src/sound/mixer/mixer.s

Reduces cycles to do a mixing operation from `12306` cycles to `11529` and fixes a tiny bug.
Don't know if this makes a difference, but meh, it was fun.

Tiny audio optimisation

---

agb/build.rs
agb/interrupt_handler.s

It was annoying me how hard it was to see the assembly warnings. So now print them as part of the build (currently doesn't fail the build, but I'm tempted)

Print warnings for assembler

---

agb/examples/mixer_basic.rs
agb/src/sound/mixer/mixer.s
agb/src/sound/mixer/mod.rs

Can't stop me!
Inspired by a gba mod tracker (https://github.com/kusma/pimpmobile/blob/f2b2be49e806ca2a0d99cf91b3838d6d10f86b7d/src/pimp_mixer_clip_arm.S), here's an improvement that takes us from `11881` cycles to `10915` cycles.
I used the same principles, but because the data storage is different, I needed to write it slightly differently here.

Another audio performance improvement

---

agb/src/sound/mixer/mixer.s
agb/src/sound/mixer/sw_mixer.rs
agb/src/syscall.rs

turns out rust's zeroing of buffers is really really slow on the GBA. Maybe we can do something better with that by replacing the intrinsic, but for now, a special case for the sound engine.
Brings the 32kHz basic example from 13% CPU to 6% CPU making it almost as fast as the 10512Hz was at the beginning of last week.

Speed up sound attempt 209

---

agb/examples/mixer_32768.rs
agb/examples/stereo_sound.rs

Prints the CPU usage for the sound examples to the gba screen which lets us test the timing on real hardware.

Print text in sound examples

---

agb/src/agbabi/memcpy.s
agb/src/agbabi/mod.rs
agb/src/lib.rs

When using the new memcpy implementation, the hat chooses the wizard would crash if you died on a stage containing an enemy. After proving that the issue lies within the new memcpy implementation, I wrote a bunch of tests to see what would cause the issue.
The system would hang with misaligned copies less than 4 bytes in size, so I added a simple bypass in that case.
The tests are probably also worth keeping.

Fix agbabi memcpy issue

---

agb/src/agbabi/memset.s
agb/src/agbabi/mod.rs

Appears to not properly handle 8 byte aligned destinations? Writes some earlier bytes to align to word boundary?

a test for agbabi memset

---

agb/src/agbabi/memcpy.s
agb/src/agbabi/mod.rs

Tests a lot more permutations of input and output offsets for memcpy and memcpy4 to try and find the source of the corruption bug.
This spotted another infinite loop in agbabi's memcpy, but no memory corruption...

More memcpy tests

---

.github/scripts/publish-crate.sh

While doing some research on cargo, I found that crates.io's index can take up to 5 minutes to actually publish, which causes a slightly problem with releasing all the crates at the same time.
A really dumb way to check is to poll the crates.io index and check if the version number shows up in the result. So try this for now.

Check crate has published before continuing

---

agb/build.rs
agb/src/agbabi/macros.inc
agb/src/agbabi/memcpy.s

agbabi updated over last week, and it seems much faster and worth updating :D
The `test_all_of_memcpy` went to
`agb::agbabi::test::memcpy::test_all_of_memcpy...[ok: 57960585 c ≈ 3.45 s]`
from
`agb::agbabi::test::memcpy::test_all_of_memcpy...[ok: 99251582 c ≈ 5.91 s]`
Tests don't pass for memset, not sure if it is me or memset not working in all cases, so I'll leave updating that until after the game jam.

Update agbabi's memcpy

---

agb-macros/src/lib.rs
agb/Cargo.toml
agb/src/agb_alloc/block_allocator.rs
agb/src/agb_alloc/mod.rs
agb/src/lib.rs
examples/the-hat-chooses-the-wizard/Cargo.toml
examples/the-hat-chooses-the-wizard/src/main.rs
mgba-test-runner/build-mgba.sh
release.sh
template/Cargo.toml
template/src/main.rs

The ability to add tests in a sub-crate was requested by Jinxit in the gbadev discord. Seemed like a useful feature so here is a draft implementation for getting some feedback.
I'll add some documentation (since it isn't obvious how to enable it) once we've decided it could be a good idea :).
See the changes in main.rs in `the-hat-chooses-the-wizard` for what you have to do to enable it (also need to enable the 'testing' feature in the `dev-dependencies`)

Make it possible to run tests in target crates (and add a basic tests in hat-wizard)

---

template/Cargo.toml

Not enabling optimisations in the template can be painful, so these should be enabled. Also enable debug symbols to be in the binary for when we want to objdump it.

Better defaults for dev mode and release mode in the template

---

agb/src/display/tiled/map.rs

Removing unused tiles should happen only after they've been replaced rather than before. This should save us in the cases where dots were being rendered because that is the marker for freed memory

Run the GC after copying the tiles rather than before

---

agb/.cargo/config.toml
agb/src/lib.rs
agb/src/syscall.rs
armv4t-none-eabi.json
book/games/pong/.cargo/config.toml
examples/hyperspace-roll/.cargo/config.toml
examples/the-hat-chooses-the-wizard/.cargo/config.toml
examples/the-purple-night/.cargo/config.toml
justfile
template/.cargo/config.toml

I've found that sometimes Rust generates better-enough code for some usecases in arm mode vs. thumb mode that it becomes worth it to build my whole project with [`--target armv4t-none-eabi.json`](https://github.com/lifning/gba-flac-demo/blob/remaster/armv4t-none-eabi.json) - so here's a hopefully simple-enough way to support the BIOS calls when targeting either mode :)

Support armv4t-none-eabi target as well.

---

.vscode/agb.code-workspace
CHANGELOG.md
agb/Cargo.toml
agb/src/lib.rs
examples/the-hat-chooses-the-wizard/Cargo.toml
template/Cargo.toml

Enough people are using the `testing` feature that we should probably just make it a default. This will also be helpful for making it easy to add integration tests.

Make testing a default feature

---

.github/workflows/build-and-test.yml
.vscode/agb.code-workspace

Run CI daily with the latest nightly. This has two benefits:
* See regressions in Rust early and see changes to clippy.
* Warm up the caches for the day.

CI Schedule

---

CHANGELOG.md
agb/examples/output.rs
agb/src/interrupt.rs
agb/src/lib.rs
agb/src/sync/locks.rs
agb/src/sync/mod.rs
agb/src/sync/statics.rs

Split into a separate PR as requested in #298. This adds an `agb::sync` module that implements some GBA-specific primitives that take advantage of the fact that the only real "multi-threading" on the GBA is interrupts and otherwise, there is just the main thread.
Outstanding issues:

Implement additional synchronization primitives

---

CHANGELOG.md
agb/src/hash_map.rs

@corwinkuiper requested an implementation and it seems annoying to write without access to the internal state.
Also added implementation of size_hint for the hashmap iterators which should help with efficiency in some cases

Add implementation of `HashMap.retain` method

---

examples/hyperspace-roll/src/main.rs
examples/the-purple-night/src/main.rs

Make vscode not give me an error with hyperspace-roll and the-purple-night

---

agb-image-converter/src/rust_generator.rs

Tiles are not aligned to a 2 byte boundary despite calling dma_copy16 which requires this.
In future, should make dma_copy16 panic if arguments are not aligned in debug mode.

Align tiles to a 2 byte boundary

---

book/src/setup/linux.md

This PR fixes the linux setup guide using the wrong package name

Fix incorrect package name in Linux setup guide

---

CHANGELOG.md

Due to the release rush, we didn't add a changelog entry for 0.12.2. So here it is :)

Add changelog entry for 0.12.2

---

agb/src/lib.rs

This will require a very recent nightly as the minimum supported compiler version

remove feature not required in later nightlies

---

agb/Cargo.toml
agb/build.rs
agb/examples/text_render.rs
agb/src/agb_alloc/mod.rs
agb/src/lib.rs
agb/src/mgba.rs
agb/src/rng.rs
examples/the-hat-chooses-the-wizard/build.rs
examples/the-purple-night/build.rs

Also updates the rust edition to 2021 for agb since I couldn't do both

Fix clippy lint for inline format args

---

tools/src/release.rs

Add `--cleanup=whitespace` to keep lines starting with # in the `git tag` command for releases.

Make it so that the release tag includes the entire release notes

---

justfile

Can be quite slow documenting all the dependencies when we don't actually need to in order to test what we're trying to test

Stop building dependency docs while testing docs

---

CHANGELOG.md
agb/src/display/tiled/tiled1.rs

Fixes #367
Had missed implementations to actually get the backgrounds if you were using tiled1 mode.

Add missing methods for tiled1 to allow creating backgrounds

---

CHANGELOG.md
agb/src/sound/mixer/mixer.s
agb/src/sound/mixer/sw_mixer.rs

Fixes #371.
If the volume was zero, the calculation for leading zeros was incorrect. So both reduce the amount of work done for 0 volume and also count the leading zeros correctly in the fast path.

Fix volume zero and power of 2

---

CHANGELOG.md
agb/src/interrupt.rs
agb/src/syscall.rs

If you missed a vblank, then the next call to wait_for_vblank would pointlessly wait rather than returning immediately. Meaning if you missed a vblank by a few cycles, you'd be waiting for the entire next one :(.

Make missing a vblank interrupt wait less painful

---

CHANGELOG.md
agb/Cargo.toml
agb/examples/mixer_32768.rs
agb/examples/mixer_basic.rs
agb/examples/stereo_sound.rs
agb/src/sound/mixer/hw.rs
agb/src/sound/mixer/mod.rs
agb/src/sound/mixer/sw_mixer.rs
examples/hyperspace-roll/src/lib.rs
examples/the-hat-chooses-the-wizard/src/lib.rs
examples/the-hat-chooses-the-wizard/src/splash_screen.rs
examples/the-purple-night/src/lib.rs
examples/the-purple-night/src/sfx.rs

Simplify the audio mixer to always use the interrupt system which fixes a soundness issue (pun intended) if you forget the mixer but not the interrupt handler.

Remove option to manage your own interrupts in the mixer

---

CHANGELOG.md
agb-image-converter/src/lib.rs
agb-image-converter/src/palette16.rs

Previously `include_image!()` would only set transparent pixels to index 0 if a `transparent_color` was specified. However, this in unnecessary as the transparency index is always 0.

Fix alpha not being considered when transparent_colour was absent

---

CHANGELOG.md
agb/examples/animated_background.rs
agb/examples/chicken.rs
agb/examples/dynamic_tiles.rs
agb/examples/mixer_32768.rs
agb/examples/stereo_sound.rs
agb/examples/test_logo.rs
agb/examples/text_render.rs
agb/examples/wave.rs
agb/examples/windows.rs
agb/src/display/example_logo.rs
agb/src/display/font.rs
agb/src/display/tiled/infinite_scrolled_map.rs
agb/src/display/tiled/map.rs
agb/src/display/tiled/mod.rs
agb/src/display/tiled/tiled0.rs
agb/src/display/tiled/tiled1.rs
agb/src/display/tiled/vram_manager.rs
agb/src/lib.rs
examples/combo/src/lib.rs
examples/hyperspace-roll/src/lib.rs
examples/the-hat-chooses-the-wizard/src/lib.rs
examples/the-purple-night/src/lib.rs

Fixes #386.
Turns out we weren't correctly setting the 256 colour mode flag :facepalm:. It worked fine in affine mode because those are 256 colour mode by default, but now it'll also work for regular backgrounds.

Fix 256 colours

---

agb/Cargo.toml

This works around rust-lang/rust#108853 by using an `opt-level` of `3` rather than `s`.

workaround the rust issue

---

CHANGELOG.md
agb-macros/src/lib.rs

Generates compile error calls when something goes wrong.

Better error message for #[agb::entry] errors

---

CHANGELOG.md
agb/gba.ld
agb/gba_mb.ld
book/games/pong/gba.ld
book/games/pong/gba_mb.ld
examples/combo/gba.ld
examples/combo/gba_mb.ld
examples/hyperspace-roll/gba.ld
examples/hyperspace-roll/gba_mb.ld
examples/the-hat-chooses-the-wizard/gba.ld
examples/the-purple-night/gba.ld
examples/the-purple-night/gba_mb.ld
template/gba.ld
template/gba_mb.ld

Now required since you can use lld as the linker. However, still have the 'cannot represent a difference across sections' error :(.

Add shstrtab section for lld

---

CHANGELOG.md
agb/Cargo.toml
examples/combo/Cargo.toml
examples/hyperspace-roll/Cargo.toml
template/Cargo.toml

Reduce codegen units to 1 to ensure build works

---

agb/src/agb_alloc/block_allocator.rs
agb/src/agb_alloc/bump_allocator.rs
agb/src/agb_alloc/mod.rs
examples/hyperspace-roll/Cargo.lock
examples/the-hat-chooses-the-wizard/Cargo.lock
examples/the-purple-night/Cargo.lock

Adds growth to the block allocator.
Implements for a subset of the possible growth cases (although the remaining case we don't even handle in allocation).
Allocation benchmark (which doesn't grow) is improved for other reasons.
This growth benchmark has a 16x speedup
```rust
#[test_case]
fn growth_benchmark(_gba: &mut crate::Gba) {
let mut growing_vector = Vec::with_capacity(1);
for i in 0..1000 {
growing_vector.push(i);
growing_vector.reserve_exact(i + 2);
}
}
```

Allocator growth

---

CHANGELOG.md
agb/examples/output.rs
agb/examples/wave.rs
agb/src/agb_alloc/block_allocator.rs
agb/src/interrupt.rs
agb/src/sound/mixer/sw_mixer.rs
agb/src/sync/statics.rs

Makes interrupt sound, albeit unsafe.
Also makes allocator not pause interrupts (and therefore not interrupt safe!!!)

Interrupt soundness

---

examples/the-purple-night/src/lib.rs

A few changes to the purple night to make it so much better!
* Fixes player positioning to be in the centre, no more drastic change of position when changing directions, and you don't go all the way into walls.
* Fixes rounding of collision to round rather than floor, this means the left and right walls are more equivalent.
* Fixes the "jitter" between objects and backgrounds where objects would move by a pixel, but the background wouldn't.
- In general we're more careful to do all display changes at once rather than throughout the frame.
- Note that for future games this is the correct way of doing things.
* Fixes slime collision boxes to match the extent of the animation.
* Use more i32 rather than u16, we're not running out of memory!
* Fixes memory leak caused by dying (previously you …

Purple night fixes

---

.github/workflows/build-and-test.yml
.vscode/agb.code-workspace
CHANGELOG.md
README.md
agb-hashmap/Cargo.toml
agb-hashmap/src/lib.rs
agb/Cargo.toml
agb/src/lib.rs
book/games/pong/Cargo.lock
examples/combo/Cargo.lock
examples/hyperspace-roll/Cargo.lock
examples/the-hat-chooses-the-wizard/Cargo.lock
examples/the-purple-night/Cargo.lock
justfile
tools/src/publish.rs

Pulls out the hashmap to its own crate. Allows us to use this in interop code between agb and desktop code and also gives us the ability to run miri on it to make sure we're not running into any crazy unsoundness bugs.

Extract agb hashmap

---

agb-hashmap/src/lib.rs
agb/src/display/tiled/vram_manager.rs

We currently do lots of redundant hash calculations while changing a tile in vram. We can cache the value and then use the entry API to reuse it.

Minor speed up for tiles

---

agb-fixnum/src/lib.rs

Mentioned here that we should probably do it: https://github.com/agbrs/agb/discussions/370#discussioncomment-4650702
From decompiling, it seems that this normally happens, but lets at least ensure it if you don't have lto enabled.

Inline always in new_from_parts

---

agb/src/agb_alloc/block_allocator.rs

This only optimises the relevant blocks during normalisation.
The benchmark in CI goes from 12023166 cycles to 9260517 cycles, a decrease of 23%.

Optimise Normalisation

---

agb/Cargo.toml
agb/src/display/mod.rs
agb/src/display/object/unmanaged/attributes.rs
book/games/pong/Cargo.lock
examples/amplitude/Cargo.lock
examples/combo/Cargo.lock
examples/hyperspace-roll/Cargo.lock
examples/the-hat-chooses-the-wizard/Cargo.lock
examples/the-purple-night/Cargo.lock

Thought I'd give bilge a go rather than modular bitfield after reading this blog post: https://hecatia-elegua.github.io/blog/no-more-bit-fiddling/
not sure I'm convinced

Use bilge rather than modular-bitfield

---

agb/src/display/object/unmanaged/attributes.rs

Hide objects by default

---

CHANGELOG.md
agb/src/sound/mixer/mixer.s
agb/src/sound/mixer/sw_mixer.rs

If you do an ldmia for loading lots of samples at once, the mixer uses significantly less CPU (10% compared to previous, 19800 cycles per frame -> 17701 cycles per frame for 32768Hz).
I've also added a really simple unit test for the `collapse` function to at least gain some confidence in it.

Even faster mixer

---

agb/src/sound/mixer/mixer.s
agb/src/sound/mixer/sw_mixer.rs

I realised we don't need to zero the buffer or read the current buffer value for the first sound that we're writing per frame. Gets us from 17728 cycles per frame for 32768Hz down to 15291 cycles per frame.
From tests (and theory), this reduces the number of cycles per frame by 2,000 for 32768Hz.

Save useless zeroing of buffer

---

agb/src/sound/mixer/sw_mixer.rs

Fixes an issue where you could only play 8 sounds until it would stop entirely.

Channel counts as finished if the channel position reaches the end of the effect

---

agb/examples/save.rs

Adds a quick example for saving a some numbers in sram.

Add example for saving

---

agb/src/display/bitmap4.rs

Colors of lower values can now overwrite colors of higher values.
Before, this didn't happen, so it was impossible to clear the screen.
credit to origamiscienceguy in the GBA Dev discord for the fix.

Fix colors of higher values being unable to be overwritten by colors of lower values in Bitmap4 mode.

---

CHANGELOG.md
agb-fixnum/src/lib.rs

One of the finer cosine terms was not correct. By using the num macro (not available at the time of this functions initial writing) we can avoid issues of incorrect constants.
Fixes #497

Fix cos term

---

agb/gba.ld
agb/src/agb_alloc/mod.rs

The main thing this addresses is a bug with the `__{e,i}wram_rom_start` symbols. Defined the way they were, they did not always actually correspond to the LMA address of the section. I'm not entirely sure the exact circumstances that caused this, but I ran into examples and they caused very strange bugs because all of that ram section was then offset by a few bytes, as the routine in `.startup` copied from the wrong location in rom.
For example, using `cargo objdump -- --headers` to check the actual section addresses and comparing to the symbol addresses (which I `info!` logged out) I found an example where `__iwram_rom_start = 0x0800676c` but the actual LMA address of `.iwram` was `0x08006770`: everything was off by 4-bytes and that could be clearly seen in mgba's memory view. When it …

Fix linker scripts and their symbols

---

CHANGELOG.md
agb/src/display/tiled/mod.rs

This PR adds the ability for a palette to be set on a TileSetting struct. This is useful when doing more advanced palette tricks on a background. For example, changing the palette for only a portion of a background or manually managing screen palettes.

Allow TileSetting palette to be set

---

agb/src/lib.rs

Linter updates caused it to start complaining.

Add missing #[cfg(test)]

---

agb/src/display/bitmap4.rs

- Adds a proper clear and draw wide point functions to bitmap4 for consistency.
- I must save the bitmap modes from being removed

Add clear and draw wide point functions to bitmap4

---

agb/README.md

This is an attempt to make the readme show up on crates.io

Add a symlink for the readme to the agb directory

---

CHANGELOG.md
agb-image-converter/src/lib.rs
agb/src/display/object/sprites/sprite.rs
agb/src/lib.rs

As discussed in https://github.com/agbrs/agb/discussions/544,  this expand $OUT_DIR when used in the **include_aseprite** and **include_background_gfx** macros in order to support including from the out directory.
Example usage:
`const SPRITE_0: &Graphics = include_aseprite!("$OUT_DIR/sprite_0.aseprite");`

Expand $OUT_DIR in include_aseprite and include_background_gfx

---

CHANGELOG.md
agb/examples/mixer_basic.rs
agb/src/sound/mixer/mod.rs
agb/src/sound/mixer/sw_mixer.rs

Requested here: https://github.com/agbrs/agb/discussions/547
Added methods to pause and resume playback of audio channels, and you can use it with the mixer_basic example to prove it works.

Pause channels

---

agb/src/display/tiled/mod.rs

These methods were unused and breaking the build

px_offset_x and px_offset_y were unused

---

agb/Cargo.toml

rustc-hash isn't needed in agb itself any more

---

agb-gbafix/Cargo.lock
book/games/pong/Cargo.lock
emulator/Cargo.lock
examples/amplitude/Cargo.lock
examples/combo/Cargo.lock
examples/hyperspace-roll/Cargo.lock
examples/the-dungeon-puzzlers-lament/Cargo.lock
examples/the-hat-chooses-the-wizard/Cargo.lock
examples/the-purple-night/Cargo.lock
tools/Cargo.lock

Fixes #553 and allows building on latest nightly again.

Update ahash in the cargo.lock files.

---

template/.cargo/config.toml

- [ x] Changelog updated / no changelog update needed
This closes issue #554 and allows the template project have logging to console on by default when you run `cargo run`

Changes the default runner to log to console

---

CHANGELOG.md
agb/examples/affine_background.rs
agb/examples/animated_background.rs
agb/examples/chicken.rs
agb/examples/dynamic_tiles.rs
agb/examples/mixer_32768.rs
agb/examples/stereo_sound.rs
agb/examples/text_render.rs
agb/src/display/example_logo.rs
agb/src/display/font.rs
agb/src/display/tiled/infinite_scrolled_map.rs
agb/src/display/tiled/map.rs
agb/src/lib.rs
examples/combo/src/lib.rs
examples/hyperspace-roll/src/background.rs
examples/hyperspace-roll/src/battle.rs
examples/hyperspace-roll/src/customise.rs
examples/hyperspace-roll/src/lib.rs
examples/the-dungeon-puzzlers-lament/src/game.rs
examples/the-dungeon-puzzlers-lament/src/lib.rs
examples/the-hat-chooses-the-wizard/src/lib.rs
examples/the-hat-chooses-the-wizard/src/splash_screen.rs
examples/the-purple-night/src/lib.rs

Adds `.priority()`, `.set_priority()` and `.is_visible()` and replace `show` and `hide` with `.set_visible()` in `RegularMap`, `AffineMap` and `InfiniteScrolledMap`.

Add priority set / get and set_visible / is_visible to maps

---

CHANGELOG.md
agb/src/display/object/managed.rs
agb/src/display/object/unmanaged/attributes.rs
agb/src/display/object/unmanaged/object.rs

This exposes expose the `hflip`, `vflip`, `priority` and `position` object attribute to remove the need for storing them in separate variables.
I think it might also be worth to update the pong tutorial and maybe some of the examples to highlight this.

Expose hflip, vflip, priority, position

---

CHANGELOG.md
agb/src/display/tiled/infinite_scrolled_map.rs

Adds a useful into_inner function which we need at the moment.
Will add a changelog and documentation later

Add an into_inner() function on infinite scrolled map

---

CHANGELOG.md
agb-fixnum/src/lib.rs
agb/src/display/tiled/infinite_scrolled_map.rs

* A very old issue that meant you couldn't move more than one tile per frame.
* This fixes the logic so we can move maps quickly.

Fix the incorrect copying of map tiles issue

---

agb/src/display/tiled/infinite_scrolled_map.rs

The fix in #576 didn't quite work due to an out by one when going left or down. Seems the TODO is now complete?

Fix out by one in infinite scroll

---

tools/src/utils.rs

Clippy lint was getting upset that we were pointlessly cloning. So stop doing that (even though the lint seems to have a bug, but I'd like the build to start working again).

Fix clippy lint in agb tools

---

agb/src/dma.rs
agb/src/lib.rs

I was trying to use DMA in a less trivial case than the examples and couldn't because I couldn't write the types (since I'd forgotten to export the module).
This will likely just be 0.19.2 with the extra `pub mod` :)

Make dma module public

---

justfile
website/app/src/mgba.tsx
website/app/src/useFrameSkip.hook.ts
website/site/index.html

GitHub pages, for whatever reason, doesn't compress the combo ROM and instead serves it uncompressed. Therefore, we explicitly compress it using the highest compression level at build time and explicitly decompress it.
Previously we would download 14.69MB, now we download 7.84MB. Approximately 50% savings.

Compress combo rom

---

.github/renovate.json
justfile

Make renovate only update js dependencies once per week and to group them all in one PR.
Apparently with this branch name, renovate will validate the config for me which is fancy

Group JS updates to reduce PR spam a little

---

agb/src/panics_render/text.rs

Can cause double panic by writing OOB.

Add bounds check for panic writer

---

CHANGELOG.md
agb/Cargo.toml
agb/src/lib.rs
justfile

You probably don't want backtraces if you're doing multiboot and in a few other cases.
Also #646 broke the build if you didn't use the `testing` feature, so I've updated the `justfile` so that a CI run checks that agb builds correctly both without the `testing` feature and without the `backtrace` feature. The `backtrace` feature implies the testing feature to make things a bit simpler.

Make backtraces optional

---

CHANGELOG.md
agb/src/display/object/unmanaged/object.rs

It was annoying me how often I had to write this

Add a set_next method on OamIterator

---

book/src/SUMMARY.md
book/src/pong/03_sprites.md
book/src/setup/building.md
book/src/setup/windows.md

Closes #691
* Added Windows instruction for the setup
* fixed the path to the example, adjusted to the cargo-project name
* fixed broken code in the example
Original PR contains an extra merge commit we don't want, so this avoids that.

Add windows instructions

---

agb/src/lib.rs

Double panics could produce some interesting results, so we should probably avoid them to avoid breaking the state too much :)

Avoid double panic

---

agb/src/panics_render.rs

If the allocation for the working space and the result of the QR code fails, then we don't want to panic but just not render the QR code.

Handle failure to allocate QR code on panic

---

CHANGELOG.md
tracker/agb-xm-core/src/lib.rs

Versions of xmrs below 0.4.1 (unreleased, 0.4.2 is on crates.io but 0.4.1 is in the repo) have a bug where they swap linear and amiga frequencies. This caused all old versions of agb (which were using version 0.3) to use the amiga frequency table rather than the linear one. Technically it sounds slightly wrong but it is kinda hard to tell.
Since agb 0.20.0, we are now using xmrs 0.5, which correctly reports the frequency type for the XM file. That pointed out an error in the note_to_speed method for linear frequencies (since those are now being used). It turns out that the formula for calculating the frequency expects a 0 based index for the note, but we were passing a 1 based index for the note. Moving this down a note fixes the issue where things were being played at the wrong …

Notes are 1 indexed, not 0 indexed

---

agb/Cargo.toml

Put https://agbrs.dev as the homepage for the crate

---

CHANGELOG.md
agb/examples/dma_effect_background_colour.rs
agb/examples/dma_effect_background_scroll.rs
agb/examples/dma_effect_circular_window.rs
agb/src/dma.rs

The lifetime here is pointless since we copy the data anyway. And this makes a bunch of stuff not unsafe any more which is really nice.

Remove lifetime from dma transfer handle

---

CHANGELOG.md
agb/src/backtrace.rs
agb/src/entrypoint.s

agb-debug was producing some bad backtraces which was being caused by the fact that we were producing slightly incorrect values which made bigger examples of backtraces completely useless.
I could fix this in agb-debug, but I feel like the correct place to do this is just fixing agb.

The link register points to the next instruction, not the current one

---

agb-hashmap/Cargo.toml
agb/Cargo.toml
tracker/agb-tracker/Cargo.toml

The package published to crates.io should not include tests / examples / benches. Previously we ran into issues with having a too large package from example data, but we avoided this by making the examples smaller. A better way to avoid this is to not include them at all.

Exclude tests / examples / benches from the published packages

---

CHANGELOG.md
agb/src/display/tiled/map.rs

Fixes issue #733 where affine tilemaps have a gap.

Fix tilemap gaps in affine graphic modes #733

---

Cargo.toml

Avoids a warning in rust-analyzer and is the correct thing to do

Add template to workspace exclude

---

agb/src/agb_alloc/mod.rs
agb/src/display/object/affine.rs
agb/src/display/object/sprites/sprite.rs
agb/src/display/window.rs
agb/src/interrupt.rs
agb/src/sound/mixer/mod.rs

Clippy was complaining that our first paragraphs were too long

Shorten the first paragraphs

---

tracker/agb-xm-core/src/lib.rs

I've seen an xm file that plays fine in milkytracker and other places, but has instrument indexes which are too high. They are just treated as non-existent :)

It doesn't appear to be an error to have an invalid instrument index

---

CHANGELOG.md
agb-image-converter/src/lib.rs
agb/src/lib.rs

This PR adds the possibility for graphics imported through `include_background_gfx!` to be used as public modules, e.g.:
```rust
/// graphics.rs
agb::include_background_gfx!(pub background, "d77bba", tiles256 => 256 "map.aseprite");
/// main.rs
#![no_std]
#![no_main]
use agb::display::Priority;
use agb::display::tiled::RegularBackgroundSize::Background64x64;
use agb::display::tiled::{TiledMap, TileFormat};
mod graphics;
#[agb::entry]
fn main(mut gba: agb::Gba) -> ! {
let (tiled, mut vram) = gba.display.video.tiled1();
let vblank = agb::interrupt::VBlank::get();
let tileset = &graphics::background::tiles256.tiles;
vram.set_background_palettes(graphics::background::PALETTES);
let mut bg = tiled.regular(Priority::P2, Background64x64, TileFormat::EightBpp);
for y in 0..64u16 {
for x in …
```

Allowing imported graphics to be exposed as pub mod

---

CHANGELOG.md
tracker/agb-tracker/src/lib.rs

I've done some horrible hacks for this in our jam games. Better to have a first-party solution to stopping channels in the tracker.

Add a method to stop the tracker

---

agb-macros/src/lib.rs

Should hopefully fix the currently failing build

Mark the generated entry as doc(hidden)

---

CHANGELOG.md
tracker/agb-tracker/src/lib.rs
tracker/agb-xm-core/Cargo.toml
tracker/agb-xm/Cargo.toml
tracker/agb-xm/src/lib.rs
tracker/desktop-player/Cargo.toml
tracker/desktop-player/src/main.rs

Closes #742
Turns out XMRS will do the conversion for us, which means we can 'just support' s3m and mod file formats for free which is nice.

Upgrade xmrs which gives us s3m and mod file support

---

agb/Cargo.toml

Add fallback feature for portable-atomic.
This is needed since without it, we don't get anything that the platform doesn't natively support, which is only up to 32 bits.
We newly need to change this because once_cell no longer imports with default features.
Fixes:
```
error[E0432]: unresolved import `portable_atomic::AtomicU128`
--> src/rng.rs:1:23
|
1 | use portable_atomic::{AtomicU128, Ordering};
|                       ^^^^^^^^^^
|                       |
|                       no `AtomicU128` in the root
|                       help: a similar name exists in the module: `AtomicU8`
```

Fix build issue due to atomic u128s

---

agb-debug/src/load_dwarf.rs

Needed to fix today's clippy linting error

Don't use ok_or_else for a copy value

---

tracker/agb-xm-core/src/lib.rs

Unnecessary conversions. Seems to have actually come from a minor version bump of xmrs

Fix clippy lints from 2024-10-11

---

CHANGELOG.md
tracker/agb-xm-core/Cargo.toml
tracker/agb-xm/Cargo.toml
tracker/desktop-player/Cargo.toml

Will need to release 0.21.2 after this is merged since current no lockfile builds are failing.

Fix the xmrs version since we've had failures twice

---

agb/src/display/tiled/vram_manager.rs

This makes set_background_palette public so that one can set a specific background palette, not only write the entire bank at once with set_background_palettes.

Make set_background_palette public

---

agb/src/interrupt.rs

Don't need both no_mangle and export_name

---

CHANGELOG.md
agb/src/lib.rs

only have a panic handler when using the either of the default testing or backtrace features

---

agb/examples/output.rs
agb/tests/test_multiboot.rs
agb/tests/test_save_eeprom_512b.rs
agb/tests/test_save_eeprom_8k.rs
agb/tests/test_save_flash_128k.rs
agb/tests/test_save_flash_64k.rs
agb/tests/test_save_sram.rs
justfile
tracker/agb-tracker/src/lib.rs

We previously allowed an empty loop (`loop {}`) to make a function never return. This is a clippy warning, and probably for good reason.
I've swapped them all with `loop { syscall::halt() }` which is the more correct thing to do in an infinite loop :).

Stop allowing an empty loop

---

agb-hashmap/src/node_storage.rs
agb-hashmap/src/node_storage/vec.rs
agb/src/display/bitmap3.rs
agb/src/display/mod.rs
agb/src/display/object.rs
agb/src/display/palette16.rs
agb/src/display/tiled.rs
agb/src/display/tiled/affine_background.rs
agb/src/display/tiled/registers.rs
agb/src/display/tiled/regular_background.rs
agb/src/display/window.rs

Remove some magic u16s and replace with an actual struct which we manipulate better

Bilge in backgrounds

---

agb/src/agbabi/memcpy.s
agb/src/agbabi/memset.s

There are very minor performance improvements from this:
Before:
```
agb::agbabi::test::memcpy::test_all_of_memcpy...[ok: 53510906 c ≈ 3.19 s]
agb::agbabi::test::memcpy::test_all_of_memcpy4...[ok: 39371480 c ≈ 2.35 s]
agb::agbabi::test::memcpy::test_all_of_memcpy4_non_word_length...[ok: 45755219 c ≈ 2.73 s]
agb::agbabi::test::memcpy::test_memcpy4_with_different_sizes...[ok: 244971 c ≈ 0.01 s]
agb::agbabi::test::memset::test_memset4_with_different_sizes_and_offsets...[ok: 3326916 c ≈ 0.2 s]
agb::agbabi::test::memset::test_memset4_with_non_word_size_sizes_and_offsets...[ok: 10717390 c ≈ 0.64 s]
agb::agbabi::test::memset::test_memset_with_different_sizes_and_offsets...[ok: 2525106 c ≈ 0.15 s]
```
After:
```
agb::agbabi::test::memcpy::test_all_of_memcpy...[ok: 53494903 c ≈ 3.19 s] …
```

Update agbabi as-of 2025-02-05

---

Cargo.toml
website/backtrace/Cargo.toml

We were getting 
```
warning: profiles for the non root package will be ignored, specify profiles at the workspace root
```
as a warning in the build. Set it correctly in the workspace toml file

Fix cargo warning about profiles in the non root package

---

agb/examples/windows.rs
agb/src/display/blend.rs
agb/src/display/blend/registers.rs
agb/src/display/mod.rs
agb/src/memory_mapped.rs

The current implementation of blend doesn't quite make sense given the new paradigms we're going for. This pushes the blend configuration into the `GraphicsFrame` which means you configure your blending as you configure your backgrounds etc, which feels better to me.
I've also fixed the API to hopefully ensure that only valid modes can be done.

Blend in graphics frame

---

agb/src/display/tiled/vram_manager.rs

It's a big function that *shouldn't* (maybe) benefit from inlining too much as it depends a fair amount on global state and doesn't do any big processing with the given parameters

don't ever inline adding tile to vram

---

CHANGELOG.md
agb/examples/chicken.rs
agb/examples/mixer_32768.rs
agb/examples/save.rs
agb/examples/stereo_sound.rs
agb/examples/text_render.rs
agb/src/display/font.rs
agb/src/display/tiled/vram_manager.rs

It's technically unsafe, but rather than mark it as such, I've just removed it since it's hard to use correctly and can be better used by calling `set_background_palette` instead.

Remove `set_background_palette_raw`

---

agb/src/display/font.rs
agb/src/display/tiled/vram_manager.rs

Dynamic tile was always `'static` which is actually correct now. This mostly fixes it by forcing the `'static` lifetime.

Partially fix dynamic tile

---

agb-image-converter/src/rust_generator.rs
agb/examples/dynamic_tiles.rs
agb/examples/mixer_32768.rs
agb/examples/stereo_sound.rs
agb/examples/text_render.rs
agb/src/display/font.rs
agb/src/display/tiled.rs
agb/src/display/tiled/regular_background.rs
agb/src/display/tiled/vram_manager.rs

Required a new method on regular background tiles `set_tile_dynamic` sadly. But with it now you can't let the tile run out of scope while it's still visible :).

Fully fix dynamic tile

---

agb-image-converter/src/rust_generator.rs
agb/examples/chicken.rs
agb/examples/dynamic_tiles.rs
agb/examples/mixer_32768.rs
agb/examples/object_text_render.rs
agb/examples/save.rs
agb/examples/stereo_sound.rs
agb/examples/text_render.rs
agb/src/display/mod.rs
agb/src/display/object/sprites/sprite.rs
agb/src/no_game.rs
examples/amplitude/src/lib.rs
examples/the-dungeon-puzzlers-lament/src/game.rs

It seems a bit silly to have a special module for `Palette16`, so I've pulled it into the `display` module.

Move Palette16 to the display module

---

agb/examples/dma_effect_circular_window.rs
agb/examples/windows.rs
agb/src/display/mod.rs
agb/src/display/tiled.rs
agb/src/display/tiled/regular_background.rs
agb/src/display/tiled/vram_manager.rs

Added rustdoc comments for regular backgrounds. Could probably do with some more examples, but that can come later.

Rustdoc comments for regular backgrounds

---

agb/src/display/tiled/affine_background.rs
agb/src/display/tiled/regular_background.rs

Removing first could take the reference count to 0, and add it to the GC
queue to be processed at GC time. However, if we're then adding the same
tile back on, it doesn't get removed from the GC queue.
By adding the new tile on, and then removing the old one, if it's the
same tile, we just increase the reference count to 2 and then back down
to 1.
Setting a tile to itself is a reasonably common operation, and it isn't
that uncommon for tiles to be unique across the screen too, so hopefully
this'll improve performance and either way is probably the cause of the
incredibly bad performance of the old tile rendering before the more
recent refactor (in addition to the other horribly inefficient code that
was there).

Hopefully improve performance of add_tile

---

agb/examples/infinite_scrolled_map.rs
agb/src/display/tiled/infinite_scrolled_map.rs
examples/combo/src/lib.rs
examples/the-hat-chooses-the-wizard/src/lib.rs
examples/the-purple-night/src/lib.rs

Also renames `set_pos` to `set_scroll_pos`

Rustdoc comments for infinite scrolled map

---

agb/examples/dma_effect_circular_window.rs
agb/examples/windows.rs
agb/src/display/window.rs

We're not consistent about `set_position` and `set_pos`. Standardising on `set_pos`, but I haven't updated objects because @corwinkuiper is currently working on those and I don't want to make him sad with merge conflicts.

Rename set_position to set_pos in windows

---

agb/src/display/tiled/regular_background.rs

It wasn't very clear what the assumptions of the method were. So improve the docs around `fill_with`.

Clarify `fill_with` for `RegularBackgroundTiles`

---

CHANGELOG.md
agb-fixnum/Cargo.toml
agb-fixnum/src/lib.rs
agb-macros/src/lib.rs

Now that you can use floats in const contexts, we can mess around with floats inside `num!` and be able to put constant expressions in there rather than just float literals.

Const fn num macro

---

agb-fixnum/Cargo.toml
agb-fixnum/build.rs
agb-fixnum/src/lib.rs

Presumably it's faster with a LUT. It won't work with an i8 any more but I can't imagine it was being used.

implement cos using a LUT

---

agb-image-converter/src/lib.rs

Delete the docs from agb-image-converter so it doesn't appear twice in agb

---

agb/src/dma.rs
justfile

The new method required exactly 160 values which isn't actually what we want. We want at least 160 values.
Also update the screenshot generation to generate a screenshot on frame 100 rather than 10 because we have a few examples which require more setup time (mainly the new dma ones)

Fix dma when passing more than 160 values

---

agb/src/display/tiled/affine_background.rs
agb/src/display/tiled/regular_background.rs
agb/src/display/tiled/vram_manager.rs
agb/src/display/tiled/vram_manager/tile_allocator.rs

Affine backgrounds require their tiles to be within the first 256 tiles. This is a pain, and currently only happens by accident in agb.
This PR addresses this issue by allocating all regular tiles to _after_ the first 256 tiles, and then to the first 256 tiles if that runs out of space. It leaves affine tiles to go in the first 256 tiles.

Better affine tile allocation

---

CHANGELOG.md
agb/src/lib.rs
agb/src/mgba.rs
agb/src/print.rs

I removed it (and replaced it with recommendation to use the `println!` macro and the new `eprintln!` macro)

'Document' mgba module

---

agb-hashmap/src/lib.rs
agb/src/lib.rs

They looked a bit weird in the documentation. This is much neater

Inline the docs for agb-hashmap

---

agb/examples/dma_effect_affine_background_3d_plane.rs
agb/examples/dma_effect_affine_background_pipe.rs
agb/examples/dma_effect_background_blob_monster.rs
agb/examples/dma_effect_background_colour.rs
agb/examples/dma_effect_background_desert.rs
agb/examples/dma_effect_background_magic_spell.rs
agb/examples/dma_effect_circular_window.rs
agb/src/display/tiled/vram_manager.rs
agb/src/dma.rs
agb/src/interrupt.rs
agb/src/lib.rs
agb/src/timer.rs

Adds documentation for the remaining undocumented parts of agb.
Could still use more comprehensive module level docs.
Doc test for Dma would be nice, none of the examples are really short enough to include here though.

Document everything in agb

---

justfile

We were running them twice, since `cargo test` now runs doctests even in non-default targets. Fixed in cargo since about a week ago :D

Doctests are now run by default

---

agb-fixnum/build.rs
agb-fixnum/src/num.rs

This matters for rotations where we often want 12 bits of precision.
Graph of the differences from the test:

Linearly interpolate `cos` if the precision is bigger than 8

---

agb/examples/blend_rain.rs
agb/src/display/blend.rs
agb/src/display/mod.rs

Removes `BlendLayer` because I don't think that was helping. You can now set up any blend with a single call to `.blend()`.
I'd like to do the same for windows but that's proving to be a little trickier

Blend API minor restructure

---

template/src/main.rs

1. Remove the section about the allocator being disable-able
2. Add `extern crate alloc;` to the default template
3. Remove the `mut` because having it warn by default is a bit sad

Clean up template comments

---

agb/examples/affine_object.rs
agb/examples/affine_transformations.rs
agb/src/display/object.rs
agb/src/display/object/affine.rs
agb/src/display/object/unmanaged/object.rs
book/src/articles/affine.md
book/src/articles/objects_deep_dive.md
examples/amplitude/src/lib.rs

To be added to the changelog...

Only expose `AffineMatrixInstance` which is now called `AffineMatrixObject`

---

agb/examples/affine_object.rs
agb/examples/affine_transformations.rs
agb/examples/dma_effect_affine_background_pipe.rs
agb/src/display/affine.rs
agb/src/display/blend.rs
agb/src/display/object/affine.rs
agb/src/display/tiled/affine_background.rs
agb/src/display/window.rs
book/src/articles/affine.md

There were too many generics. I've made the API slightly less flexible but now you don't have to state as many pointless generics.

Simplify affine matrix generics

---

book/book.toml
book/src/agb.css
book/src/agb.js

I thought a table of contents would be nice. I also thought it would be nice if links in the book would open in new tabs rather than losing your current position.
I did this in pure JS because adding mdbook-toc dependencies or similar is really heavyweight with how long it adds to the build, whereas this is basically free.

Add a table of contents and external links to the book

---

agb-fixnum/src/num.rs
agb-fixnum/src/rect.rs
agb-fixnum/src/vec2.rs
agb-hashmap/src/hash_set.rs
agb-hashmap/src/lib.rs

Hi, I submitted #1003 and I found some other code comment inconsistencies.
In agb-master/agb-hashmap/src/lib.rs, the comment indicates that code will panic if capacity > 2^32 * 0.85.
```rust
/// # Panics
///
/// Panics if capacity is larger than 2^32 * .85
#[must_use]
pub fn with_capacity_in(capacity: usize, alloc: ALLOCATOR) -> Self {
for i in 0..32 {
let attempted_size = 1usize << i;
if number_before_resize(attempted_size) > capacity {
return Self::with_size_in(attempted_size, alloc);
}
}
panic!(
"Failed to come up with a size which satisfies capacity {}",
capacity
);
}
const fn number_before_resize(capacity: usize) -> usize {
capacity * 60 / 100
}
```
But following test will failed(3650722201=2^32 * 0.85).
```rust
#[test]
fn test(){
let _ = HashMap::<i32, i32, …
```

Fix comment errors and add some tests

---

examples/the-purple-night/Cargo.toml
examples/the-purple-night/src/lib.rs

* We prefer slotmap in our newer games, it's an easy enough change to use it in purple night.
* Also fixes a bug where it flashes an image when enemies die.

Purple night use slotmap

---

agb/src/display/blend.rs
agb/src/display/mod.rs
agb/src/display/tiled.rs

We were doing the tile GC before updating the tile data in VRAM because otherwise we'd free the tiles, removing the last reference and causing them to disappear.
Now we don't free the tile data until after `commit` is finished, which allows us to run the tile GC much later in the process, which is better because we have a strict vblank deadline to finish committing, but GC can overrun that time.

Do tile gc at a more sensible time

---

website/agb/src/app/page.tsx

Adds a link from the main page to the examples now that we should be happy with them in the next version of agb.
Note that as the website releases all the time, this will apply to the live site if merged using the old examples as the content. Decide if this is okay.

add link to examples

---

book/book.toml
book/src/agb.css
book/src/articles/misc.md

Add a section about `agb::println!` and fix the table of contents

Println section

---

agb/src/display/affine.rs

Remove OverflowError since it isn't used any more

---

agb/examples/save.rs

Checking the logs for the playground server I noticed one had failed to build.
The underlying reason being not having agb_fixnum in the template crate we use, which we have decided we shouldn't be using anyway.
This won't fix what's on the website, it will only be fixed in the next release.

use agb::fixnum rather than agb_fixnum in example

---

CHANGELOG.md
agb/src/display/tiled/infinite_scrolled_map.rs

Also include a method `show_if_done()` which saves having to work out if the show call should be called at all.
Fixes #1028

Add a method for getting the infinite scrolled map update status.

---

CHANGELOG.md
agb/src/sound/mixer/mod.rs
agb/src/sound/mixer/sw_mixer.rs

Small performance improvement (about 10%) on mixer things when playing sounds slowly. Does this by copying using DMA3 into a temporary buffer if it turns out that will be faster.

DMA3 mixer speedup

---

CHANGELOG.md
agb-hashmap/src/hash_set.rs
agb-hashmap/src/lib.rs
agb-hashmap/src/node_storage.rs
agb-hashmap/src/node_storage/vec.rs
agb/src/display/object.rs
agb/src/display/object/sprites.rs
agb/src/display/object/sprites/sprite_allocator.rs
agb/src/display/tiled/vram_manager.rs
agb/src/lib.rs

This simplifies some of the initialisation too because the VRamManager and the SpriteManager can both have const constructors as well :D

Make HashMap::new() const

---

CHANGELOG.md
agb/src/refcount.rs

Fix issue introduced by https://github.com/rust-lang/rust/pull/141219

Use `into_raw_with_allocator`

---

agb-hashmap/src/node.rs

Code would panic if current distance <= 0 so I modified comment from "=0" to "<=0", which would be more accurate.

Fix comment

---

CHANGELOG.md

If we're going to release just this, it should have a changelog entry

add changelog entry for nightly issue from 2025-08-12

---

book/src/articles/backgrounds.md

Added a small section on the `fill_with()` convenience function to the backgrounds deep dive article, since it was used in the pong introduction but wasn't mentioned in the deep dive.
The section reads as follows:
If the included `.aseprite` file is the exact dimensions of the GBA screen (240x160 pixels), you can also simply call [`.fill_with()`](https://docs.rs/agb/latest/agb/display/tiled/struct.RegularBackground.html#method.fill_with) on the `RegularBackground` you created with a reference to the included file:
```rust
tiles.fill_with(&background::BEACH);
```
---
One open question is whether the previous example should be changed since both now cover the same use case. It might be an idea to have the previous example iterate over `0..32` and `0..32` instead with a different referenced …

Added small section in backgrounds deep dive about `fill_with()`
